import assert from "node:assert/strict";
import test from "node:test";
import { assertBusinessOperationPayloadHash, validateBusinessOperationPayloadV2 } from "./business-operation-payload";

const payload={command:"legacy_payment:fence",expected_results:[{ordinal:1,entity_type:"legacy_cutover",entity_key:"cutover:payments-v1:fenced",entity_action:"fenced",action_correlation_uid:"11111111-1111-4111-8111-111111111111"}],inputs:{command_sha256:"a".repeat(64)},reservation_slots:[{local_ordinal:1,phase:0,qualified_table_name:"public.business_operation_receipts",reserved_id:"1",result_ordinal:0,slot_kind:"operation_receipt",slot_kind_order:0},{local_ordinal:1,phase:10,qualified_table_name:"public.legacy_cutover_states",reserved_id:"2",result_ordinal:1,slot_kind:"business_row",slot_kind_order:10},{local_ordinal:1,phase:30,qualified_table_name:"public.accounting_audit_events",reserved_id:"3",result_ordinal:1,slot_kind:"audit_row",slot_kind_order:30}],schema_version:"business-operation-payload-v2"} as const;

test("strict operation payload binds exact results, slots, canonical bytes and hash",()=>{const value=validateBusinessOperationPayloadV2(payload as never);assert.equal(value.catalogBound,false);assert.match(value.sha256,/^[0-9a-f]{64}$/);assert.doesNotThrow(()=>assertBusinessOperationPayloadHash(payload as never,value.sha256));});
test("catalog-bound slots require contiguous ordinals and named catalog sequences",()=>{const catalog={...payload,reservation_slots:payload.reservation_slots.map((slot,index)=>({...slot,slot_kind:index===0?"receipt":index===1?"business":"audit",slot_ordinal:index+1,sequence_name:`public.fixture_${index+1}_id_seq`}))};assert.equal(validateBusinessOperationPayloadV2(catalog as never).catalogBound,true);assert.throws(()=>validateBusinessOperationPayloadV2({...catalog,reservation_slots:catalog.reservation_slots.map((slot,index)=>index===1?{...slot,slot_ordinal:3}:slot)} as never),/catalog_slot_invalid/);});
test("extra keys, numeric reserved IDs, noncontiguous results and hash drift fail closed",()=>{assert.throws(()=>validateBusinessOperationPayloadV2({...payload,extra:true} as never),/shape_invalid/);assert.throws(()=>validateBusinessOperationPayloadV2({...payload,reservation_slots:payload.reservation_slots.map((slot,index)=>index===1?{...slot,reserved_id:2}:slot)} as never),/slot_invalid/);assert.throws(()=>validateBusinessOperationPayloadV2({...payload,expected_results:[{...payload.expected_results[0],ordinal:2}]} as never),/result_invalid/);assert.throws(()=>assertBusinessOperationPayloadHash(payload as never,"0".repeat(64)),/hash_mismatch/);});
test("receipt, kind, order and one-audit-per-result closure fail closed",()=>{
  assert.throws(()=>validateBusinessOperationPayloadV2({...payload,reservation_slots:payload.reservation_slots.slice(1)} as never),/receipt_slot_invalid/);
  assert.throws(()=>validateBusinessOperationPayloadV2({...payload,reservation_slots:payload.reservation_slots.map((slot,index)=>index===1?{...slot,slot_kind:"free_text"}:slot)} as never),/slot_invalid/);
  assert.throws(()=>validateBusinessOperationPayloadV2({...payload,reservation_slots:[payload.reservation_slots[0],payload.reservation_slots[2],payload.reservation_slots[1]]} as never),/slot_order_invalid/);
  assert.throws(()=>validateBusinessOperationPayloadV2({...payload,reservation_slots:payload.reservation_slots.slice(0,2)} as never),/audit_bijection_invalid/);
  assert.throws(()=>validateBusinessOperationPayloadV2({...payload,reservation_slots:[...payload.reservation_slots,payload.reservation_slots[2]]} as never),/slot_order_invalid|audit_bijection_invalid/);
});
