import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { normalizeDeferredSourceRowV2, type DeferredMappingV2 } from "./adapters/deferred-source-normalization-v2";
import { sourceFingerprint, validateSourcePreviewInput, type SourcePreviewInput } from "./source-preview-contract-v2";
import { canonicalJson, sha256, type CanonicalValue } from "./source-contracts";

test("foreign-faculty v3 binds the reproducible profile without changing candidate-only semantics", () => {
  const profileBytes = readFileSync("docs/source-contracts/profiles/group-foreign-faculty-2025-v3.json", "utf8"); const profile = JSON.parse(profileBytes) as Record<string, CanonicalValue>; const profilePreimage = { ...profile }; delete profilePreimage.profile_sha256;
  const mappingBytes = readFileSync("docs/source-contracts/mappings/group-foreign-faculty-2025-v3.json", "utf8"); const mapping = JSON.parse(mappingBytes) as unknown as DeferredMappingV2;
  assert.equal(profileBytes, `${canonicalJson(profile)}\n`); assert.equal(profile.profile_sha256, sha256(canonicalJson(profilePreimage))); assert.equal(mapping.source_profile_sha256, profile.profile_sha256); assert.equal(mapping.adapter_code, "group-roster-v3");
  const result = normalizeDeferredSourceRowV2(mapping, { coordinateKey: "sheet:test:row:3", recordKind: "allocation_roster", values: { 졸업기수: "41기", "성  명": "관리자 표시 이름" } });
  assert.equal(result.envelope.normalized_payload.proposed_amount, "50000"); assert.equal(result.envelope.normalized_payload.allocation_status, "candidate_only"); assert.equal(result.envelope.normalized_payload.member_name_snapshot, "관리자 표시 이름"); assert.match(String(result.envelope.normalized_payload.member_name_key_digest), /^[0-9a-f]{64}$/); assert.doesNotMatch(mappingBytes, /ACCOUNTING_PII_HMAC_KEY_V1|createHmac/i);
});

test("foreign-faculty v3 release is self-bound but authorizes no source decision", () => {
  const mappingBytes = readFileSync("docs/source-contracts/mappings/group-foreign-faculty-2025-v3.json"); const approvalBytes = readFileSync("docs/source-contracts/approvals/group-foreign-faculty-2025-v3.json", "utf8"); const approval = JSON.parse(approvalBytes) as Record<string, CanonicalValue>; const approvalPreimage = { ...approval }; delete approvalPreimage.receipt_sha256;
  const descriptorBytes = readFileSync("docs/source-contracts/releases/group-foreign-faculty-2025-v3.json"); const descriptor = JSON.parse(descriptorBytes.toString("utf8")) as Record<string, CanonicalValue>; const planBytes = readFileSync("docs/source-contracts/releases/group-foreign-faculty-development-release-plan-v3.json", "utf8"); const plan = JSON.parse(planBytes) as Record<string, CanonicalValue>; const planPreimage = { ...plan }; delete planPreimage.plan_sha256;
  assert.equal(approval.receipt_sha256, sha256(canonicalJson(approvalPreimage))); assert.equal(approval.mapping_sha256, sha256(mappingBytes)); assert.ok((approval.decision_scope as CanonicalValue[]).includes("no_source_decision")); assert.equal(descriptor.mapping_approval_receipt_sha256, approval.receipt_sha256); assert.equal(plan.descriptor_sha256, sha256(descriptorBytes)); assert.equal(plan.plan_sha256, sha256(canonicalJson(planPreimage))); assert.equal(planBytes, `${canonicalJson(plan)}\n`);
});

test("delegated conservative decision permits only two quarantine items per candidate", () => {
  const receipt = JSON.parse(readFileSync("docs/source-contracts/approvals/group-foreign-faculty-source-decision-v3.json", "utf8")) as Record<string, CanonicalValue>; const receiptPreimage = { ...receipt }; delete receiptPreimage.receipt_sha256; assert.equal(receipt.receipt_sha256, sha256(canonicalJson(receiptPreimage))); assert.equal(receipt.delegation_text_sha256, sha256("이번 같은 승인도 네가 해줘. 굳이 내가 할 필요가 없는 승인 같은데?")); assert.equal(receipt.pending_exact_primary_receipt_equality, true);
  const payload = { generation: 41, group_key_digest: "a".repeat(64), group_name_snapshot: "외래교수회", member_name_key_digest: "b".repeat(64), member_name_snapshot: "관리자 표시 이름", proposed_amount: "50000" };
  const input: SourcePreviewInput = { schema_version: "accounting-source-preview-input-v2", source_code: "GROUP_FOREIGN_FACULTY_2025", source_uid: "26a45b1a-fc67-5b1e-aca4-6391dc296bf1", release_uid: "95a32819-1d37-4bfc-b472-685b733511e2", source_revision: "test", source_fingerprint: "0".repeat(64), operation_uid: "11111111-1111-4111-8111-111111111111", batch_uid: "22222222-2222-4222-8222-222222222222", decision_set_uid: "33333333-3333-4333-8333-333333333333", captured_timezone: "Asia/Seoul", coverage_from: "2025-01-01T00:00:00+09:00", coverage_through: "2026-03-01T00:00:00+09:00", rows: [{ coordinate_key: "sheet:test:row:3", coordinate_normalization_version: "coordinate-v1", issue_status: "warning", normalization_version: "group-roster-v3@3.0.0+reproducible-profile-v1", normalized_payload: payload, raw_payload: payload, source_display_snapshot: "2025", decisions: [{ decision_kind: "member_match", decision_payload: { candidate_member_uid_or_null: null, case_uid: "44444444-4444-4444-8444-444444444444", evidence_digest: "c".repeat(64), evidence_kind: "name_only", outcome: "quarantine", score_basis: "name_only_unapprovable" } }, { decision_kind: "group_allocation", decision_payload: { allocation_kind_or_null: null, allocation_request_uid_or_null: null, amount_or_null: null, assessment_uid_or_null: null, dues_year_or_null: null, group_member_uid_or_null: null, member_uid_or_null: null, outcome: "quarantine", primary_bank_batch_uid_or_null: null, primary_bank_coordinate_key_or_null: null, receipt_uid_or_null: null } }] }] }; input.source_fingerprint = sourceFingerprint(input); assert.equal(validateSourcePreviewInput(input).rows[0].decisions.length, 2);
});
