import assert from "node:assert/strict";
import test from "node:test";
import type { PoolClient } from "pg";
import { materializeReceiptRefund } from "./receipt-refund-write";

const actor={userId:7,userUid:"11111111-1111-4111-8111-111111111111",name:"synthetic admin",authorizationVersion:"a".repeat(64)};
const receiptUid="22222222-2222-4222-8222-222222222222",refundEventUid="33333333-3333-4333-8333-333333333333",originalUid="44444444-4444-4444-8444-444444444444",newUid="55555555-5555-4555-8555-555555555555";
class Fixture{calls:Array<{sql:string;params?:unknown[]}>=[];next=100;constructor(private readonly eventStatus="proposed"){}client={query:async(sql:string,params?:unknown[])=>{this.calls.push({sql:sql.replace(/\s+/g," ").trim(),params});if(sql.startsWith("SELECT current_setting"))return{rowCount:1,rows:[{transaction_isolation:"serializable"}]};if(sql.includes("FROM public.users"))return{rowCount:1,rows:[{id:7,user_uid:actor.userUid,name:actor.name,is_admin:true}]};if(sql.includes("FROM public.dues_receipts"))return{rowCount:1,rows:[{id:"10",event_id:"20",gross_amount:"50000",status:"approved"}]};if(sql.includes("FROM public.dues_allocations")&&sql.includes("request_uid=ANY"))return{rowCount:1,rows:[{id:"30",request_uid:originalUid,amount:"50000",allocation_kind:"dues",assessment_id:null,dues_year:2026,effective_at:"2026-01-01T00:00:00+09:00",group_member_id:null,member_id:"40",receipt_id:"10",status:"approved"}]};if(sql.includes("FROM public.economic_events"))return{rowCount:1,rows:[{id:"50",event_uid:refundEventUid,amount:"50000",occurred_at:"2026-01-15T12:00:00+09:00",direction:"debit",status:this.eventStatus,reverses_event_id:"20",bound_claims:1,bank_transactions:1}]};if(sql.startsWith("SELECT nextval"))return{rowCount:1,rows:[{id:String(this.next++)}]};if(sql.startsWith("INSERT")||sql.startsWith("UPDATE"))return{rowCount:1,rows:[]};throw new Error(`unexpected:${sql}`);}}as unknown as Pick<PoolClient,"query">;}
function input(overrides:Record<string,unknown>={}){return{refundEventUid,receiptUid,originalAllocationRequestUids:[originalUid],newAllocationRequestUids:[newUid],correctionReasonCode:null,correctionEvidenceSha256:null,correctionEvidenceVerified:false,actor,...overrides};}

test("ordinary refund derives next-month time from locked rows and reserves after every lock",async()=>{const fixture=new Fixture();const result=await materializeReceiptRefund(fixture.client,input());assert.equal(result.rightsEffectMode,"next_month_negative");assert.deepEqual(result.effectiveTimes,["2026-02-01T00:00:00+09:00"]);const eventLock=fixture.calls.findIndex((call)=>call.sql.includes("FROM public.economic_events"));const reserve=fixture.calls.findIndex((call)=>call.sql.startsWith("SELECT nextval"));assert.ok(reserve>eventLock);assert.match(fixture.calls[eventLock].sql,/AT TIME ZONE 'Asia\/Seoul'/);assert.match(fixture.calls.find((call)=>call.sql.includes("request_uid=ANY"))!.sql,/AT TIME ZONE 'Asia\/Seoul'/);const allocationInsert=fixture.calls.find((call)=>call.sql.startsWith("INSERT INTO public.dues_allocations"));assert.equal(allocationInsert?.params?.[4],null);assert.equal(allocationInsert?.params?.[6],"2026-02-01T00:00:00+09:00");assert.equal(allocationInsert?.params?.[19],"next_month_negative");});

test("verified coded correction copies original effective time and exact code",async()=>{const fixture=new Fixture();const result=await materializeReceiptRefund(fixture.client,input({correctionReasonCode:"source_error",correctionEvidenceSha256:"b".repeat(64),correctionEvidenceVerified:true}));assert.equal(result.rightsEffectMode,"retroactive_error");assert.deepEqual(result.effectiveTimes,["2026-01-01T00:00:00+09:00"]);const allocationInsert=fixture.calls.find((call)=>call.sql.startsWith("INSERT INTO public.dues_allocations"));assert.equal(allocationInsert?.params?.[4],"source_error");assert.equal(allocationInsert?.params?.[19],"retroactive_error");});

test("unverified correction and non-proposed refund event fail before reservation",async()=>{await assert.rejects(materializeReceiptRefund(new Fixture().client,input({correctionReasonCode:"false_transaction",correctionEvidenceSha256:"c".repeat(64),correctionEvidenceVerified:false})),/receipt_refund_correction_evidence_invalid/);const fixture=new Fixture("approved");await assert.rejects(materializeReceiptRefund(fixture.client,input()),/receipt_refund_event_binding_mismatch/);assert.equal(fixture.calls.some((call)=>call.sql.startsWith("SELECT nextval")),false);});
