import type { PoolClient } from "pg";
import { canonicalJson, sha256, type CanonicalValue } from "./source-contracts";
import type { GroupMultiBatchApplyPlan } from "./source-decision-group-plan";
import type { GroupExecutionReservation } from "./source-decision-group-materialization";

export type GroupMaterializationActor = { userId: number; userUid: string; name: string; authorizationVersion: string };
export type GroupSourceSpineResult = { groupCoordinateKey: string; partyId: string; classificationUid: string; claimUid: string; eventId: string; eventUid: string; provenanceId: string; bankTransactionId: string };

function fail(code:string):never{throw new Error(code);}
function step(reservation:GroupExecutionReservation,coordinate:string,suffix:string){const value=reservation.steps.find((candidate)=>candidate.groupCoordinateKey===coordinate&&candidate.key.endsWith(suffix));if(!value)fail("source_decision_group_source_spine_step_missing");return value;}
function actorArgs(actor:GroupMaterializationActor,at:string,correlationUid:string):unknown[]{return [at,actor.authorizationVersion,correlationUid,actor.name,actor.userUid,actor.userId];}

export async function executeGroupSourceSpines(client:Pick<PoolClient,"query">,plan:GroupMultiBatchApplyPlan,reservation:GroupExecutionReservation,actor:GroupMaterializationActor,decidedAt:string):Promise<GroupSourceSpineResult[]>{
  if(!plan.resolvedBindings||!Number.isFinite(Date.parse(decidedAt)))fail("source_decision_group_source_spine_input_invalid");
  const results:GroupSourceSpineResult[]=[];
  for(const group of [...plan.groups].sort((left,right)=>Buffer.compare(Buffer.from(left.primaryCoordinateKey),Buffer.from(right.primaryCoordinateKey)))){
    const evidence=group.primaryEvidence;const digests=plan.resolvedBindings.financialDigestsByCoordinate[group.primaryCoordinateKey];if(!evidence||!group.occurredAt||!group.postedDate||!digests)fail("source_decision_group_source_spine_input_invalid");
    const partyStep=reservation.steps.find((candidate)=>candidate.groupCoordinateKey===group.primaryCoordinateKey&&candidate.key.endsWith(":party"));let partyId=plan.resolvedBindings.eventPartyIdsByUid[group.eventPartyUid];
    if(partyStep){await client.query(`INSERT INTO public.economic_event_parties (id,party_kind,party_uid,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,stable_code,status) OVERRIDING SYSTEM VALUE VALUES ($1,'group',$2::uuid,$3::timestamptz,$4,$5::uuid,$6,'admin',$7::uuid,$8,NULL,'active')`,[partyStep.rowId,group.eventPartyUid,...actorArgs(actor,decidedAt,partyStep.correlationUid)]);partyId=partyStep.rowId;}
    if(!partyId)fail("source_decision_group_source_spine_party_missing");
    const alias=step(reservation,group.primaryCoordinateKey,":alias");await client.query(`INSERT INTO public.economic_event_party_aliases (id,decision_item_id,party_digest,party_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,$5::timestamptz,$6,$7::uuid,$8,'admin',$9::uuid,$10,$11)`,[alias.rowId,evidence.decisionItemId,digests.payerDigest,partyId,...actorArgs(actor,decidedAt,alias.correlationUid),evidence.sourceRowVersionId]);
    const classification=step(reservation,group.primaryCoordinateKey,":classification");const splits=[...group.categorySplits].sort((left,right)=>Buffer.compare(Buffer.from(`${left.categoryCode}\0${left.amount}`),Buffer.from(`${right.categoryCode}\0${right.amount}`))).map((split,index)=>({ordinal:index+1,category_code:split.categoryCode,amount:split.amount}));const classificationResult=await client.query<{classification_uid:string}>(`INSERT INTO public.source_row_classification_decisions (id,category_splits,classification_kind,coordinate_id,decision_actor_at,decision_actor_authorization_version,decision_actor_correlation_uid,decision_actor_name_snapshot,decision_actor_scope,decision_actor_uid_snapshot,decision_actor_user_id,decision_item_id,decision_payload_sha256,direction,dues_year,effective_at,event_kind,event_party_id,member_id,party_kind,source_row_version_id,status,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2::jsonb,$3,$4,$5::timestamptz,$6,$7::uuid,$8,'admin',$9::uuid,$10,$11,$12,'credit',$13,$5::timestamptz,'bank',$14,NULL,'group',$15,'approved',NULL,1) RETURNING classification_uid::text`,[classification.rowId,canonicalJson(splits as unknown as CanonicalValue),group.classificationKind,evidence.coordinateId,...actorArgs(actor,decidedAt,classification.correlationUid),evidence.decisionItemId,group.classificationDecisionPayloadSha256,group.duesYear,partyId,evidence.sourceRowVersionId]);if(classificationResult.rowCount!==1)fail("source_decision_group_source_spine_classification_missing");
    const claimOpen=step(reservation,group.primaryCoordinateKey,":claim-open");const candidateKey=sha256(canonicalJson({candidate_key_version:"event-candidate-v2",party_identity:`event-party:${group.eventPartyUid.toLowerCase()}`,dues_year_or_null:group.duesYear,amount:group.eventAmount,occurred_date_kst:group.postedDate,direction:"credit",party_kind:"group"}));const claimResult=await client.query<{claim_uid:string}>(`INSERT INTO public.economic_event_claims (id,amount,candidate_key,claim_actor_at,claim_actor_authorization_version,claim_actor_correlation_uid,claim_actor_name_snapshot,claim_actor_scope,claim_actor_uid_snapshot,claim_actor_user_id,coordinate_id,created_at,direction,dues_year,effective_at,event_id,event_party_id,member_id,occurred_date_kst,party_kind,source_row_version_id,state,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9,$10,$4::timestamptz,'credit',$11,$4::timestamptz,NULL,$12,NULL,$13::date,'group',$14,'open',NULL,1) RETURNING claim_uid::text`,[claimOpen.rowId,group.eventAmount,candidateKey,...actorArgs(actor,decidedAt,claimOpen.correlationUid),evidence.coordinateId,group.duesYear,partyId,group.postedDate,evidence.sourceRowVersionId]);if(claimResult.rowCount!==1)fail("source_decision_group_source_spine_claim_missing");
    const event=step(reservation,group.primaryCoordinateKey,":event-create");const eventResult=await client.query<{event_uid:string}>(`INSERT INTO public.economic_events (id,amount,direction,dues_year,event_kind,occurred_at,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,reverses_event_id,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,'credit',$3,'bank',$4::timestamptz,$5::timestamptz,$6,$7::uuid,$8,'admin',$9::uuid,$10,NULL,'proposed') RETURNING event_uid::text`,[event.rowId,group.eventAmount,group.duesYear,group.occurredAt,...actorArgs(actor,decidedAt,event.correlationUid)]);if(eventResult.rowCount!==1)fail("source_decision_group_source_spine_event_missing");
    const claimBound=step(reservation,group.primaryCoordinateKey,":claim-bound");await client.query(`INSERT INTO public.economic_event_claims (id,amount,candidate_key,claim_uid,coordinate_id,created_at,decision_actor_at,decision_actor_authorization_version,decision_actor_correlation_uid,decision_actor_name_snapshot,decision_actor_scope,decision_actor_uid_snapshot,decision_actor_user_id,direction,dues_year,effective_at,event_id,event_party_id,member_id,occurred_date_kst,party_kind,source_row_version_id,state,supersedes_id,version) OVERRIDING SYSTEM VALUE SELECT $1,amount,candidate_key,claim_uid,coordinate_id,created_at,$2::timestamptz,$3,$4::uuid,$5,'admin',$6::uuid,$7,direction,dues_year,$2::timestamptz,$8,event_party_id,member_id,occurred_date_kst,party_kind,source_row_version_id,'bound',id,2 FROM public.economic_event_claims WHERE id=$9`,[claimBound.rowId,...actorArgs(actor,decidedAt,claimBound.correlationUid),event.rowId,claimOpen.rowId]);
    const provenance=step(reservation,group.primaryCoordinateKey,":provenance");const provenanceDigest=sha256(canonicalJson({digest_version:"event-provenance-v1",event_uid:eventResult.rows[0].event_uid,source_row_content_digest:evidence.contentDigest,evidence_role:"authority_candidate",authority_rank_snapshot:300,normalization_version:evidence.normalizationVersion!}));await client.query(`INSERT INTO public.economic_event_provenance (id,authority_rank_snapshot,event_id,evidence_digest,evidence_role,normalization_version,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,300,$2,$3,'authority_candidate',$4,$5::timestamptz,$6,$7::uuid,$8,'admin',$9::uuid,$10,$11)`,[provenance.rowId,event.rowId,provenanceDigest,evidence.normalizationVersion,...actorArgs(actor,decidedAt,provenance.correlationUid),evidence.sourceRowVersionId]);
    const authority=step(reservation,group.primaryCoordinateKey,":authority");await client.query(`INSERT INTO public.economic_event_authority_decisions (id,decision_actor_at,decision_actor_authorization_version,decision_actor_correlation_uid,decision_actor_name_snapshot,decision_actor_scope,decision_actor_uid_snapshot,decision_actor_user_id,decision_kind,effective_at,event_id,reason_code,selected_provenance_id,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2::timestamptz,$3,$4::uuid,$5,'admin',$6::uuid,$7,'select',$2::timestamptz,$8,'HIGHEST_AUTHORITY_SELECTED',$9,NULL,1)`,[authority.rowId,...actorArgs(actor,decidedAt,authority.correlationUid),event.rowId,provenance.rowId]);
    const transaction=step(reservation,group.primaryCoordinateKey,":bank-transaction");const balance=evidence.normalizedPayload.balance_after;await client.query(`INSERT INTO public.bank_transactions (id,account_id,balance_after,event_id,occurred_at,posted_date,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,row_fingerprint,source_row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,$5::timestamptz,$6::date,$7::timestamptz,$8,$9::uuid,$10,'admin',$11::uuid,$12,$13,$14)`,[transaction.rowId,plan.resolvedBindings.bankAccountId,balance,event.rowId,group.occurredAt,group.postedDate,...actorArgs(actor,decidedAt,transaction.correlationUid),digests.rowFingerprint,evidence.sourceRowVersionId]);
    results.push({groupCoordinateKey:group.primaryCoordinateKey,partyId,classificationUid:classificationResult.rows[0].classification_uid,claimUid:claimResult.rows[0].claim_uid,eventId:event.rowId,eventUid:eventResult.rows[0].event_uid,provenanceId:provenance.rowId,bankTransactionId:transaction.rowId});
  }
  return results;
}
