import type { PoolClient } from "pg";
import type { GroupExecutionReservation } from "./source-decision-group-materialization";
import type { GroupMultiBatchApplyPlan } from "./source-decision-group-plan";
import type { GroupMaterializationActor, GroupSourceSpineResult } from "./source-decision-group-source-spine";

function fail(code:string):never{throw new Error(code);}
function step(reservation:GroupExecutionReservation,coordinate:string,suffix:string){const found=reservation.steps.find((candidate)=>candidate.groupCoordinateKey===coordinate&&candidate.key.endsWith(suffix));if(!found)fail("source_decision_group_financial_step_missing");return found;}
function actor(actor:GroupMaterializationActor,at:string,correlation:string):unknown[]{return [at,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId];}

export async function executeGroupFinancialGraphs(client:Pick<PoolClient,"query">,plan:GroupMultiBatchApplyPlan,reservation:GroupExecutionReservation,spines:GroupSourceSpineResult[],recordedActor:GroupMaterializationActor,decidedAt:string):Promise<void>{
  if(!plan.resolvedBindings||spines.length!==plan.groups.length)fail("source_decision_group_financial_input_invalid");
  for(const group of [...plan.groups].sort((left,right)=>Buffer.compare(Buffer.from(left.primaryCoordinateKey),Buffer.from(right.primaryCoordinateKey)))){
    const spine=spines.find((candidate)=>candidate.groupCoordinateKey===group.primaryCoordinateKey);const evidence=group.primaryEvidence;const digests=plan.resolvedBindings.financialDigestsByCoordinate[group.primaryCoordinateKey];if(!spine||!evidence||!group.occurredAt||!digests)fail("source_decision_group_financial_input_invalid");
    const cashbookSteps=[];for(const split of [...group.categorySplits].sort((left,right)=>Buffer.compare(Buffer.from(left.categoryCode),Buffer.from(right.categoryCode)))){const created=step(reservation,group.primaryCoordinateKey,`:cashbook:${split.categoryCode}:create`);const category=plan.resolvedBindings.categoriesByCoordinate[group.primaryCoordinateKey][split.categoryCode];await client.query(`INSERT INTO public.cashbook_entries (id,amount,category_id,category_label_snapshot,corrects_entry_id,description_digest,direction,event_id,period_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,NULL,$5,'credit',$6,$7,$8::timestamptz,$9,$10::uuid,$11,'admin',$12::uuid,$13,'draft')`,[created.rowId,split.amount,category.id,category.displayName,digests.descriptionDigest,spine.eventId,plan.resolvedBindings.periodIdsByCoordinate[group.primaryCoordinateKey],...actor(recordedActor,decidedAt,created.correlationUid)]);cashbookSteps.push({created,approved:step(reservation,group.primaryCoordinateKey,`:cashbook:${split.categoryCode}:approve`)});}
    const receipt=step(reservation,group.primaryCoordinateKey,":receipt-create");await client.query(`INSERT INTO public.dues_receipts (id,decision_item_id,event_id,gross_amount,legacy_decision_id,receipt_uid,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,NULL,$5::uuid,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,'proposed')`,[receipt.rowId,evidence.decisionItemId,spine.eventId,group.eventAmount,group.receiptUid,...actor(recordedActor,decidedAt,receipt.correlationUid)]);
    const paymentGroup=step(reservation,group.primaryCoordinateKey,":payment-group-create");await client.query(`INSERT INTO public.dues_payment_groups (id,expected_total,payer_digest,receipt_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,roster_batch_id,snapshot_digest,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,$5::timestamptz,$6,$7::uuid,$8,'admin',$9::uuid,$10,$11,$12,'proposed')`,[paymentGroup.rowId,group.eventAmount,digests.payerDigest,receipt.rowId,...actor(recordedActor,decidedAt,paymentGroup.correlationUid),plan.resolvedBindings.rosterBatchIdsByUid[group.rosterBatchUid],digests.snapshotDigest]);
    for(const allocation of [...group.allocations].sort((left,right)=>Buffer.compare(Buffer.from(left.coordinateKey),Buffer.from(right.coordinateKey)))){
      const item=allocation.evidence;if(!item)fail("source_decision_group_financial_input_invalid");const prefix=`:member:${allocation.coordinateKey}`;const matchCase=step(reservation,group.primaryCoordinateKey,`${prefix}:match-case-create`);const matchCandidate=step(reservation,group.primaryCoordinateKey,`${prefix}:match-candidate-create`);const groupMember=step(reservation,group.primaryCoordinateKey,`${prefix}:group-member-create`);const candidateApproval=step(reservation,group.primaryCoordinateKey,`${prefix}:match-candidate-approve`);const caseApproval=step(reservation,group.primaryCoordinateKey,`${prefix}:match-case-approve`);const memberApproval=step(reservation,group.primaryCoordinateKey,`${prefix}:group-member-approve`);const allocationCreate=step(reservation,group.primaryCoordinateKey,`${prefix}:allocation-create`);const allocationApproval=step(reservation,group.primaryCoordinateKey,`${prefix}:allocation-approve`);const memberId=plan.resolvedBindings.memberIdsByUid[allocation.memberUid];const nameDigest=String(item.normalizedPayload.member_name_key_digest);const generation=String(item.normalizedPayload.generation);
      await client.query(`INSERT INTO public.member_match_cases (id,case_uid,decision_item_id,effective_at,opened_at,reason_code,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id,status,subject_generation_snapshot,subject_kind,subject_name_digest,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,$3,$4::timestamptz,$4::timestamptz,'SOURCE_MATCH_REQUIRED',$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9,$10,'candidate',$11,'group_roster',$12,NULL,1)`,[matchCase.rowId,allocation.caseUid,item.memberMatchDecisionItemId,...actor(recordedActor,decidedAt,matchCase.correlationUid),item.sourceRowVersionId,generation,nameDigest]);
      await client.query(`INSERT INTO public.member_match_candidates (id,case_uid_snapshot,decision_item_id,evidence_digest,evidence_kind,member_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,root_case_id,score_basis,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,$3,$4,$5,$6,$7::timestamptz,$8,$9::uuid,$10,'admin',$11::uuid,$12,$13,$14,'candidate')`,[matchCandidate.rowId,allocation.caseUid,item.memberMatchDecisionItemId,allocation.evidenceDigest,allocation.evidenceKind,memberId,...actor(recordedActor,decidedAt,matchCandidate.correlationUid),matchCase.rowId,allocation.scoreBasis]);
      await client.query(`INSERT INTO public.dues_group_members (id,decision_item_id,display_name_digest,effect_kind,effective_at,group_id,group_member_uid,match_candidate_id,match_case_id,match_status,member_id,proposed_amount,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,'include',$4::timestamptz,$5,$6::uuid,$7,$8,'candidate',NULL,$9,$4::timestamptz,$10,$11::uuid,$12,'admin',$13::uuid,$14,$15,NULL,1)`,[groupMember.rowId,item.allocationDecisionItemId,nameDigest,group.occurredAt,paymentGroup.rowId,allocation.groupMemberUid,matchCandidate.rowId,matchCase.rowId,allocation.amount,recordedActor.authorizationVersion,groupMember.correlationUid,recordedActor.name,recordedActor.userUid,recordedActor.userId,item.sourceRowVersionId]);
      await client.query(`UPDATE public.member_match_candidates SET status='approved',decision_actor_at=$1::timestamptz,decision_actor_authorization_version=$2,decision_actor_correlation_uid=$3::uuid,decision_actor_name_snapshot=$4,decision_actor_scope='admin',decision_actor_uid_snapshot=$5::uuid,decision_actor_user_id=$6 WHERE id=$7`,[...actor(recordedActor,decidedAt,candidateApproval.correlationUid),matchCandidate.rowId]);
      await client.query(`INSERT INTO public.member_match_cases (id,case_uid,decision_actor_at,decision_actor_authorization_version,decision_actor_correlation_uid,decision_actor_name_snapshot,decision_actor_scope,decision_actor_uid_snapshot,decision_actor_user_id,decision_item_id,effective_at,opened_at,reason_code,source_row_version_id,status,subject_generation_snapshot,subject_kind,subject_name_digest,supersedes_id,version) OVERRIDING SYSTEM VALUE SELECT $1,case_uid,$2::timestamptz,$3,$4::uuid,$5,'admin',$6::uuid,$7,decision_item_id,$2::timestamptz,opened_at,'MATCH_APPROVED',source_row_version_id,'approved',subject_generation_snapshot,subject_kind,subject_name_digest,id,2 FROM public.member_match_cases WHERE id=$8`,[caseApproval.rowId,...actor(recordedActor,decidedAt,caseApproval.correlationUid),matchCase.rowId]);
      await client.query(`INSERT INTO public.dues_group_members (id,decision_actor_at,decision_actor_authorization_version,decision_actor_correlation_uid,decision_actor_name_snapshot,decision_actor_scope,decision_actor_uid_snapshot,decision_actor_user_id,decision_item_id,display_name_digest,effect_kind,effective_at,group_id,group_member_uid,match_candidate_id,match_case_id,match_status,member_id,proposed_amount,source_row_version_id,supersedes_id,version) OVERRIDING SYSTEM VALUE SELECT $1,$2::timestamptz,$3,$4::uuid,$5,'admin',$6::uuid,$7,decision_item_id,display_name_digest,effect_kind,effective_at,group_id,group_member_uid,match_candidate_id,$8,'approved',$9,proposed_amount,source_row_version_id,id,2 FROM public.dues_group_members WHERE id=$10`,[memberApproval.rowId,...actor(recordedActor,decidedAt,memberApproval.correlationUid),caseApproval.rowId,memberId,groupMember.rowId]);
      await client.query(`INSERT INTO public.dues_allocations (id,allocation_kind,amount,assessment_id,correction_group_uid,correction_kind,correction_reason_code,decision_item_id,dues_year,effect_kind,effective_at,funding_event_id,group_member_id,legacy_decision_id,member_id,receipt_id,receipt_reversal_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,recorded_at,request_uid,reverses_allocation_id,rights_effect_mode,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,NULL,NULL,NULL,NULL,$4,$5,'payment',$6::timestamptz,NULL,$7,NULL,$8,$9,NULL,$10::timestamptz,$11,$12::uuid,$13,'admin',$14::uuid,$15,$10::timestamptz,$16::uuid,NULL,'immediate_positive','proposed')`,[allocationCreate.rowId,allocation.allocationKind,allocation.amount,item.allocationDecisionItemId,allocation.duesYear,group.occurredAt,memberApproval.rowId,memberId,receipt.rowId,...actor(recordedActor,decidedAt,allocationCreate.correlationUid),allocation.allocationRequestUid]);
      await client.query(`UPDATE public.dues_allocations SET status='approved',approval_actor_at=$1::timestamptz,approval_actor_authorization_version=$2,approval_actor_correlation_uid=$3::uuid,approval_actor_name_snapshot=$4,approval_actor_scope='admin',approval_actor_uid_snapshot=$5::uuid,approval_actor_user_id=$6 WHERE id=$7`,[...actor(recordedActor,decidedAt,allocationApproval.correlationUid),allocationCreate.rowId]);
    }
    for(const item of cashbookSteps)await client.query(`UPDATE public.cashbook_entries SET status='approved',approval_actor_at=$1::timestamptz,approval_actor_authorization_version=$2,approval_actor_correlation_uid=$3::uuid,approval_actor_name_snapshot=$4,approval_actor_scope='admin',approval_actor_uid_snapshot=$5::uuid,approval_actor_user_id=$6 WHERE id=$7`,[...actor(recordedActor,decidedAt,item.approved.correlationUid),item.created.rowId]);
    for(const [suffix,table,id] of [[":receipt-approve","dues_receipts",receipt.rowId],[":payment-group-approve","dues_payment_groups",paymentGroup.rowId],[":event-approve","economic_events",spine.eventId]] as const){const approved=step(reservation,group.primaryCoordinateKey,suffix);await client.query(`UPDATE public.${table} SET status='approved',approval_actor_at=$1::timestamptz,approval_actor_authorization_version=$2,approval_actor_correlation_uid=$3::uuid,approval_actor_name_snapshot=$4,approval_actor_scope='admin',approval_actor_uid_snapshot=$5::uuid,approval_actor_user_id=$6 WHERE id=$7`,[...actor(recordedActor,decidedAt,approved.correlationUid),id]);}
  }
}
