import assert from "node:assert/strict";
import test from "node:test";
import { loadIndividualApplyPlans, type IndividualDecisionItem } from "./source-decision-individual-plan";
import { projectIndividualOperation, reserveIndividualExecution } from "./source-decision-individual-materialization";

const memberUid="11111111-1111-4111-8111-111111111111";const coordinateKey="bank:toss:synthetic:1";const normalized={amount:"50000",balance_after:"50000",direction:"credit",occurred_at:"2026-01-01T00:00:00+09:00",payer_name_key_digest:"a".repeat(64),posted_date:"2026-01-01",provider_row_id:coordinateKey,transaction_description_digest:"b".repeat(64)};
const base={decisionItemId:"1",coordinateId:"2",coordinateKey,sourceRowVersionId:"3",contentDigest:"c".repeat(64),normalizationVersion:"bank-v3",normalizedPayload:normalized};
const items:IndividualDecisionItem[]=[{...base,decisionKind:"classification",decisionPayload:{allocation_request_uid_or_null:"22222222-2222-4222-8222-222222222222",category_splits:[{amount:"50000",category_code:"DUES_INCOME"}],classification_kind:"dues",direction:"credit",dues_year_or_null:2026,event_kind:"bank",event_party_uid_or_null:null,group_roster_batch_uid_or_null:null,member_uid_or_null:memberUid,outcome:"approve",party_kind:"member",receipt_uid_or_null:"33333333-3333-4333-8333-333333333333",refund_receipt_uid_or_null:null,reverses_event_uid_or_null:null}},{...base,decisionItemId:"4",decisionKind:"member_match",decisionPayload:{candidate_member_uid_or_null:memberUid,case_uid:"44444444-4444-4444-8444-444444444444",evidence_digest:"d".repeat(64),evidence_kind:"bank_payer_reference",outcome:"approve",score_basis:"exact_bank_payer_alias"}}];

function planClient(){return{query:async(sql:string)=>{if(sql.includes("FROM public.association_members"))return{rowCount:1,rows:[{id:"10",member_uid:memberUid,status:"active"}]};if(sql.includes("bank_source_account_mappings"))return{rowCount:1,rows:[{account_id:"20",account_code:"TOSS_GENERAL",source_code_snapshot:"BANK_TOSS_2026",account_code_snapshot:"TOSS_GENERAL"}]};if(sql.includes("FROM public.accounting_categories"))return{rowCount:1,rows:[{id:"30",display_name:"회비수입",active_from:"2025-01-01",active_to:null,dues_effect:"dues_credit"}]};if(sql.includes("FROM public.accounting_periods"))return{rowCount:1,rows:[{id:"40",starts_at:"2025-01-01T00:00:00+09:00",ends_at:null}]};return{rowCount:0,rows:[]};}};}

test("locks a same-coordinate member match before an individual dues plan",async()=>{const plans=await loadIndividualApplyPlans(planClient() as never,"BANK_TOSS_2026",items);assert.equal(plans.length,1);assert.equal(plans[0].memberId,"10");assert.equal(plans[0].amount,"50000");assert.equal(plans[0].categoryId,"30");assert.equal(plans[0].periodId,"40");});
test("rejects mismatched member evidence before business reservation",async()=>{const changed=structuredClone(items);changed[1].coordinateId="999";await assert.rejects(()=>loadIndividualApplyPlans(planClient() as never,"BANK_TOSS_2026",changed),/source_decision_individual_member_match_binding_mismatch/);});
test("projects individual dependency actions with one audit per result",async()=>{const plans=await loadIndividualApplyPlans(planClient() as never,"BANK_TOSS_2026",items);const reserveClient={next:1,query:async(_sql:string,values:unknown[])=>{const table=String(values[0]).slice(7);return{rowCount:1,rows:[{id:String(reserveClient.next++),sequence_name:`public.${table}_id_seq`}]};}};const reservation=await reserveIndividualExecution(reserveClient as never,plans,"55555555-5555-4555-8555-555555555555","66666666-6666-4666-8666-666666666666","77777777-7777-4777-8777-777777777777","50","60");const projection=projectIndividualOperation(reservation);assert.equal(projection.expectedResults.length,20);assert.equal(projection.reservationSlots.filter((slot)=>slot.phase===30).length,20);assert.equal(projection.reservationSlots.filter((slot)=>slot.phase===10).length,13);});
