import type { PoolClient } from "pg";
import { canonicalJson, sha256, type CanonicalValue } from "./source-contracts";

type JsonObject = Record<string, CanonicalValue>;
export type IndividualDecisionItem = { decisionItemId:string; coordinateId:string; coordinateKey:string; sourceRowVersionId:string; contentDigest:string; normalizationVersion:string; normalizedPayload:JsonObject; decisionKind:string; decisionPayload:JsonObject };
export type IndividualApplyPlan = {
  coordinateKey:string;memberId:string;memberUid:string;caseUid:string;receiptUid:string;allocationRequestUid:string;duesYear:number;amount:string;occurredAt:string;postedDate:string;classificationKind:string;classificationPayloadSha256:string;
  evidenceKind:string;evidenceDigest:string;scoreBasis:string;subjectNameDigest:string;balanceAfter:string|null;rowFingerprint:string;descriptionDigest:string;bankAccountId:string;periodId:string;categoryId:string;categoryLabel:string;
  classificationEvidence:IndividualDecisionItem;matchEvidence:IndividualDecisionItem;
};

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;const SHA=/^[0-9a-f]{64}$/;const MONEY=/^[1-9][0-9]*$/;
const SCORE_BY_EVIDENCE:Record<string,string>={existing_fk:"exact_existing_user_fk",roster_member_uid:"exact_roster_member_uid",canonical_email:"exact_canonical_email",canonical_phone:"exact_canonical_phone",canonical_mobile:"exact_canonical_mobile",board_roster_row:"exact_board_name_generation_position",bank_payer_reference:"exact_bank_payer_alias",manual_document:"manual_document_reference"};
function fail(code:string):never{throw new Error(code);}function compare(a:string,b:string){return Buffer.compare(Buffer.from(a),Buffer.from(b));}

export async function loadIndividualApplyPlans(client:Pick<PoolClient,"query">,sourceCode:string,items:IndividualDecisionItem[]):Promise<IndividualApplyPlan[]>{
  if(!["BANK_TOSS_2026","BANK_IBK_2026"].includes(sourceCode))return [];
  const classifications=items.filter((item)=>item.decisionKind==="classification"&&item.decisionPayload.outcome==="approve"&&item.decisionPayload.group_roster_batch_uid_or_null===null&&item.decisionPayload.party_kind==="member");
  if(classifications.length===0)return [];
  const drafts=classifications.map((classification)=>{const payload=classification.decisionPayload;const normalized=classification.normalizedPayload;const match=items.find((item)=>item.coordinateKey===classification.coordinateKey&&item.decisionKind==="member_match");
    if(!match||match.decisionPayload.outcome!=="approve"||match.coordinateId!==classification.coordinateId||match.sourceRowVersionId!==classification.sourceRowVersionId||match.contentDigest!==classification.contentDigest||canonicalJson(match.normalizedPayload)!==canonicalJson(normalized))fail("source_decision_individual_member_match_binding_mismatch");
    const memberUid=payload.member_uid_or_null;const receiptUid=payload.receipt_uid_or_null;const allocationUid=payload.allocation_request_uid_or_null;const caseUid=match.decisionPayload.case_uid;const evidenceKind=match.decisionPayload.evidence_kind;const evidenceDigest=match.decisionPayload.evidence_digest;const scoreBasis=match.decisionPayload.score_basis;
    if(payload.event_kind!=="bank"||payload.direction!=="credit"||payload.classification_kind!=="dues"||payload.event_party_uid_or_null!==null||payload.reverses_event_uid_or_null!==null||payload.refund_receipt_uid_or_null!==null||!UUID.test(String(memberUid))||!UUID.test(String(receiptUid))||!UUID.test(String(allocationUid))||!UUID.test(String(caseUid))||match.decisionPayload.candidate_member_uid_or_null!==memberUid||typeof evidenceKind!=="string"||SCORE_BY_EVIDENCE[evidenceKind]!==scoreBasis||typeof evidenceDigest!=="string"||!SHA.test(evidenceDigest))fail("source_decision_individual_shape_invalid");
    if(!Array.isArray(payload.category_splits)||payload.category_splits.length!==1)fail("source_decision_individual_category_invalid");const split=payload.category_splits[0];if(!split||Array.isArray(split)||typeof split!=="object")fail("source_decision_individual_category_invalid");const category=split as JsonObject;const amount=category.amount;
    if(category.category_code!=="DUES_INCOME"||typeof amount!=="string"||!MONEY.test(amount)||normalized.amount!==amount||normalized.direction!=="credit"||!Number.isInteger(payload.dues_year_or_null)||Number(payload.dues_year_or_null)<=0)fail("source_decision_individual_amount_invalid");
    const occurredAt=normalized.occurred_at;const postedDate=normalized.posted_date;const payerDigest=normalized.payer_name_key_digest;const descriptionDigest=normalized.transaction_description_digest;const providerRowId=normalized.provider_row_id;const balanceAfter=normalized.balance_after;
    if(typeof occurredAt!=="string"||!Number.isFinite(Date.parse(occurredAt))||typeof postedDate!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(postedDate)||new Date(Date.parse(occurredAt)+9*60*60*1000).toISOString().slice(0,10)!==postedDate||typeof payerDigest!=="string"||!SHA.test(payerDigest)||typeof descriptionDigest!=="string"||!SHA.test(descriptionDigest)||typeof providerRowId!=="string"||!providerRowId||balanceAfter!==null&&(typeof balanceAfter!=="string"||!/^\d+$/.test(balanceAfter)))fail("source_decision_individual_financial_evidence_invalid");
    return {coordinateKey:classification.coordinateKey,memberId:"",memberUid:String(memberUid),caseUid:String(caseUid),receiptUid:String(receiptUid),allocationRequestUid:String(allocationUid),duesYear:Number(payload.dues_year_or_null),amount,occurredAt,postedDate,classificationKind:String(payload.classification_kind),classificationPayloadSha256:sha256(canonicalJson(payload)),evidenceKind,evidenceDigest,scoreBasis:String(scoreBasis),subjectNameDigest:payerDigest,balanceAfter:balanceAfter as string|null,rowFingerprint:"",descriptionDigest,bankAccountId:"",periodId:"",categoryId:"",categoryLabel:"",classificationEvidence:classification,matchEvidence:match} satisfies IndividualApplyPlan;
  }).sort((a,b)=>compare(a.coordinateKey,b.coordinateKey));
  for(const values of [drafts.map((p)=>p.coordinateKey),drafts.map((p)=>p.caseUid),drafts.map((p)=>p.receiptUid),drafts.map((p)=>p.allocationRequestUid)])if(new Set(values).size!==values.length)fail("source_decision_individual_identity_collision");
  const memberUids=[...new Set(drafts.map((p)=>p.memberUid))].sort(compare);const members=await client.query<{id:string;member_uid:string;status:string}>("SELECT id::text,member_uid::text,status FROM public.association_members WHERE member_uid=ANY($1::uuid[]) ORDER BY member_uid FOR UPDATE",[memberUids]);if(members.rowCount!==memberUids.length||members.rows.some((m,i)=>m.member_uid!==memberUids[i]||m.status!=="active"))fail("source_decision_individual_member_binding_missing");
  const mapping=await client.query<{account_id:string;account_code:string;source_code_snapshot:string;account_code_snapshot:string}>(`SELECT a.id::text account_id,a.account_code,m.source_code_snapshot,m.account_code_snapshot FROM public.accounting_logical_sources s JOIN public.bank_source_account_mappings m ON m.logical_source_id=s.id JOIN public.bank_accounts a ON a.id=m.account_id WHERE s.source_code=$1 FOR UPDATE OF s,m,a`,[sourceCode]);if(mapping.rowCount!==1||mapping.rows[0].source_code_snapshot!==sourceCode||mapping.rows[0].account_code_snapshot!==mapping.rows[0].account_code)fail("source_decision_individual_bank_account_binding_mismatch");
  const categories=await client.query<{id:string;display_name:string;active_from:string;active_to:string|null;dues_effect:string}>("SELECT id::text,display_name,active_from::text,active_to::text,dues_effect FROM public.accounting_categories WHERE status='approved' AND category_code='DUES_INCOME' ORDER BY active_from FOR UPDATE");const periods=await client.query<{id:string;starts_at:string;ends_at:string|null}>("SELECT id::text,starts_at::text,ends_at::text FROM public.accounting_periods WHERE status='open' ORDER BY starts_at FOR UPDATE");
  const collisions=[await client.query("SELECT case_uid FROM public.member_match_cases WHERE case_uid=ANY($1::uuid[]) FOR UPDATE",[drafts.map((p)=>p.caseUid)]),await client.query("SELECT receipt_uid FROM public.dues_receipts WHERE receipt_uid=ANY($1::uuid[]) FOR UPDATE",[drafts.map((p)=>p.receiptUid)]),await client.query("SELECT request_uid FROM public.dues_allocations WHERE request_uid=ANY($1::uuid[]) FOR UPDATE",[drafts.map((p)=>p.allocationRequestUid)])];if(collisions.some((r)=>r.rowCount!==0))fail("source_decision_individual_identity_collision");
  const memberByUid=Object.fromEntries(members.rows.map((m)=>[m.member_uid,m.id]));return drafts.map((plan)=>{const category=categories.rows.filter((c)=>c.active_from<=plan.postedDate&&(c.active_to===null||plan.postedDate<c.active_to));const period=periods.rows.filter((p)=>Date.parse(p.starts_at)<=Date.parse(plan.occurredAt)&&(p.ends_at===null||Date.parse(plan.occurredAt)<Date.parse(p.ends_at)));if(category.length!==1||category[0].dues_effect!=="dues_credit"||period.length!==1)fail("source_decision_individual_effective_binding_mismatch");const rowFingerprint=sha256(canonicalJson({digest_version:"bank-row-v1",account_code:mapping.rows[0].account_code,provider_row_id:plan.classificationEvidence.normalizedPayload.provider_row_id,source_content_digest:plan.classificationEvidence.contentDigest,posted_date:plan.postedDate,occurred_at:plan.occurredAt,direction:"credit",amount:plan.amount,balance_after:plan.balanceAfter}));return {...plan,memberId:memberByUid[plan.memberUid],bankAccountId:mapping.rows[0].account_id,periodId:period[0].id,categoryId:category[0].id,categoryLabel:category[0].display_name,rowFingerprint};});
}
