import { createHash, randomUUID } from "node:crypto";
import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { google } from "googleapis";
import { normalizeDeferredSourceRowV2, type DeferredMappingV2 } from "../server/accounting/adapters/deferred-source-normalization-v2";
import { sourceKeyDigest, sourceText } from "../server/accounting/adapters/admin-readable-source-v2";
import { sourceFingerprint, validateSourcePreviewInput, type SourcePreviewInput } from "../server/accounting/source-preview-contract-v2";
import { canonicalJson, sha256, type CanonicalValue } from "../server/accounting/source-contracts";

const SPREADSHEET_ID = "1s8x9Oli94iD0Dwx1OYedmKbwSBRPkvcg3tjCML6iHPY";
const SOURCE_UID = "26a45b1a-fc67-5b1e-aca4-6391dc296bf1";
const RELEASE_UID = "95a32819-1d37-4bfc-b472-685b733511e2";
const PROFILE_PATH = "docs/source-contracts/profiles/group-foreign-faculty-2025-v3.json";
const MAPPING_PATH = "docs/source-contracts/mappings/group-foreign-faculty-2025-v3.json";
const DECISION_PATH = "docs/source-contracts/approvals/group-foreign-faculty-source-decision-v3.json";
type Profile = { source_revision: string; tabs: Array<{ header_candidates: Array<{ row: number; values_sha256: string }>; max_column: number; max_row: number; tab_id: string; title: string }> };
type Decision = { candidate_fingerprint: string; candidate_row_count: number; pending_exact_primary_receipt_equality: boolean; receipt_sha256: string } & Record<string, CanonicalValue>;
function fail(code: string): never { throw new Error(code); }
function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) fail(`missing_argument:${name}`); return process.argv[index + 1]; }
function text(value: unknown): string { return sourceText(value as CanonicalValue) ?? ""; }
function sha(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function columnName(column: number): string { let value = column; let result = ""; while (value > 0) { value -= 1; result = String.fromCharCode(65 + (value % 26)) + result; value = Math.floor(value / 26); } return result; }
function tabRange(title: string, range: string): string { return `'${title.replaceAll("'", "''")}'!${range}`; }
function deterministicUuidV4(seed: string): string { const bytes = createHash("sha256").update(seed).digest().subarray(0, 16); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; const hex = bytes.toString("hex"); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; }

async function main() {
  const output = arg("--output"); if (!(output.startsWith("/tmp/") || output.startsWith("/private/tmp/")) || existsSync(output)) fail("foreign_faculty_output_invalid");
  const profile = JSON.parse(readFileSync(PROFILE_PATH, "utf8")) as Profile; const mapping = JSON.parse(readFileSync(MAPPING_PATH, "utf8")) as DeferredMappingV2; const decision = JSON.parse(readFileSync(DECISION_PATH, "utf8")) as Decision; const decisionPreimage = { ...decision }; delete decisionPreimage.receipt_sha256; if (decision.receipt_sha256 !== sha256(canonicalJson(decisionPreimage)) || decision.candidate_row_count !== 26 || decision.pending_exact_primary_receipt_equality !== true) fail("foreign_faculty_decision_receipt_invalid"); const tab = profile.tabs[0];
  const credentials = { type: "service_account", project_id: "dynamic-waters-446615-e5", private_key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"), client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL, token_uri: "https://oauth2.googleapis.com/token" }; if (!credentials.private_key || !credentials.client_email) fail("google_service_account_unavailable"); const auth = new google.auth.GoogleAuth({ credentials, scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly", "https://www.googleapis.com/auth/drive.metadata.readonly"] }); const sheets = google.sheets({ version: "v4", auth });
  const [drive, metadata, headerResult] = await Promise.all([google.drive({ version: "v3", auth }).files.get({ fileId: SPREADSHEET_ID, fields: "version,modifiedTime" }), sheets.spreadsheets.get({ spreadsheetId: SPREADSHEET_ID, fields: "sheets(properties(sheetId,title,gridProperties(rowCount,columnCount)))" }), sheets.spreadsheets.values.get({ spreadsheetId: SPREADSHEET_ID, range: tabRange(tab.title, `A2:${columnName(tab.max_column)}2`), valueRenderOption: "FORMATTED_VALUE" })]);
  const revision = `drive-version:${drive.data.version};modified:${drive.data.modifiedTime}`; if (revision !== profile.source_revision) fail("foreign_faculty_profile_revision_stale"); const provider = (metadata.data.sheets ?? []).filter((sheet) => String(sheet.properties?.sheetId) === tab.tab_id); if (provider.length !== 1 || provider[0].properties?.title !== tab.title || provider[0].properties?.gridProperties?.rowCount !== tab.max_row || provider[0].properties?.gridProperties?.columnCount !== tab.max_column) fail("foreign_faculty_tab_profile_drift"); const header = headerResult.data.values?.[0] ?? []; if (sha(header) !== tab.header_candidates[0].values_sha256) fail("foreign_faculty_header_profile_drift");
  const required = ["졸업기수", "성  명"] as const; const positions = Object.fromEntries(required.map((name) => [name, header.flatMap((value, index) => text(value) === text(name) ? [index + 1] : [])])); if (positions["졸업기수"].length < 1 || positions["성  명"].length !== 1) fail("foreign_faculty_header_contract_mismatch"); const ranges = required.map((name) => tabRange(tab.title, `${columnName(positions[name][0])}3:${columnName(positions[name][0])}28`)); const columns = (await sheets.spreadsheets.values.batchGet({ spreadsheetId: SPREADSHEET_ID, ranges, valueRenderOption: "UNFORMATTED_VALUE", dateTimeRenderOption: "SERIAL_NUMBER" })).data.valueRanges ?? [];
  const generations = (columns[0].values ?? []).map((row) => row[0] ?? null); const names = (columns[1].values ?? []).map((row) => row[0] ?? null); const rows: SourcePreviewInput["rows"] = []; const candidates: CanonicalValue[] = [];
  for (let index = 0; index < 26; index += 1) { const coordinateKey = `sheet:${SPREADSHEET_ID}:${tab.tab_id}:row:${index + 3}`; const generationText = text(generations[index]); const name = text(names[index]); const generationMatch = generationText.match(/\d+/); if (!generationMatch || !name) fail("foreign_faculty_required_value_missing"); const normalized = normalizeDeferredSourceRowV2(mapping, { coordinateKey, recordKind: "allocation_roster", values: { 졸업기수: generationText, "성  명": name } }).envelope.normalized_payload; const { allocation_status: _candidateOnly, ...payload } = normalized; const memberNameDigest = sourceKeyDigest("allocation-member-name-key", name, true)!; candidates.push({ coordinate_key: coordinateKey, generation: Number(generationMatch[0]), member_name_key_digest: memberNameDigest, proposed_amount: "50000" }); const evidenceDigest = sha256(canonicalJson({ coordinate_key: coordinateKey, evidence_kind: "name_only", generation: Number(generationMatch[0]), member_name_key_digest: memberNameDigest, source_code: "GROUP_FOREIGN_FACULTY_2025" })); rows.push({ coordinate_key: coordinateKey, coordinate_normalization_version: "coordinate-v1", issue_status: "warning", normalization_version: "group-roster-v3@3.0.0+reproducible-profile-v1", normalized_payload: payload, raw_payload: payload, source_display_snapshot: tab.title, decisions: [{ decision_kind: "member_match", decision_payload: { candidate_member_uid_or_null: null, case_uid: deterministicUuidV4(`foreign-faculty-member-match-v1\n${coordinateKey}`), evidence_digest: evidenceDigest, evidence_kind: "name_only", outcome: "quarantine", score_basis: "name_only_unapprovable" } }, { decision_kind: "group_allocation", decision_payload: { allocation_kind_or_null: null, allocation_request_uid_or_null: null, amount_or_null: null, assessment_uid_or_null: null, dues_year_or_null: null, group_member_uid_or_null: null, member_uid_or_null: null, outcome: "quarantine", primary_bank_batch_uid_or_null: null, primary_bank_coordinate_key_or_null: null, receipt_uid_or_null: null } }] }); }
  if (sha256(canonicalJson(candidates)) !== decision.candidate_fingerprint) fail("foreign_faculty_candidate_fingerprint_mismatch"); const input: SourcePreviewInput = { schema_version: "accounting-source-preview-input-v2", source_code: "GROUP_FOREIGN_FACULTY_2025", source_uid: SOURCE_UID, release_uid: RELEASE_UID, source_revision: revision, source_fingerprint: "0".repeat(64), operation_uid: randomUUID(), batch_uid: randomUUID(), decision_set_uid: randomUUID(), captured_timezone: "Asia/Seoul", coverage_from: "2025-01-01T00:00:00+09:00", coverage_through: "2026-03-01T00:00:00+09:00", rows }; input.source_fingerprint = sourceFingerprint(input); validateSourcePreviewInput(input); writeFileSync(output, `${JSON.stringify(input)}\n`, { flag: "wx", mode: 0o600 }); chmodSync(output, 0o600); console.log(JSON.stringify({ schema_version: "foreign-faculty-preview-input-result-v3", source_fingerprint: input.source_fingerprint, row_count: rows.length, member_match_quarantine_count: rows.length, group_allocation_quarantine_count: rows.length, decision_item_count: rows.length * 2, candidate_amount_total: "1300000", primary_receipt_binding_present: false, allowed_columns_read: 2, excluded_columns_read: 0, original_write_count: 0, output_created: true, result: "materialized" }));
}
main().catch((error) => { console.error(JSON.stringify({ schema_version: "foreign-faculty-preview-input-error-v3", error_code: error instanceof Error ? error.message : "unknown", original_write_count: 0, output_created: false, result: "rejected" })); process.exitCode = 1; });
