import { createHash, randomUUID } from "node:crypto";
import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { google } from "googleapis";
import { normalizeBankRowV3 } from "../server/accounting/adapters/bank-sources-2026-v3";
import { sourceFingerprint, validateSourcePreviewInput, type SourcePreviewInput } from "../server/accounting/source-preview-contract-v2";

const SPREADSHEET_ID = "1d9C3cMd_0MomQtF5cfAk-9doVKRxsy8OKiO1MqvYqA0";
const CONFIG = {
  BANK_TOSS_2026: { profile: "docs/source-contracts/profiles/bank-toss-2026-v3.json", mapping: "docs/source-contracts/mappings/bank-toss-2026-v3.json", sourceUid: "fabdbcad-1fee-500a-80dd-68405befcaea", releaseUid: "8d1a16f6-cb53-4f7b-954f-2ecb4cc5401c", expectedRows: 200, allowed: ["거래 일시", "거래 금액", "거래 후 잔액", "적요", "거래 유형", "거래 기관", "메모"], coverageFrom: "2026-01-01T00:00:00+09:00", coverageThrough: "2026-03-17T00:00:00+09:00" },
  BANK_IBK_2026: { profile: "docs/source-contracts/profiles/bank-ibk-2026-v3.json", mapping: "docs/source-contracts/mappings/bank-ibk-2026-v3.json", sourceUid: "cdcfb582-f1e9-5bf3-91d4-eb1b8271e7c6", releaseUid: "5ad66128-5b55-4d5d-8d25-ece2291c1e82", expectedRows: 174, allowed: ["거래일시", "출금", "입금", "거래후 잔액", "상대계좌예금주명", "거래내용", "상대은행", "메모"], coverageFrom: "2026-03-16T00:00:00+09:00", coverageThrough: "2026-08-10T10:35:00Z" },
} as const;
type SourceCode = keyof typeof CONFIG;
type Profile = { source_revision: string; tabs: Array<{ header_candidates: Array<{ row: number; values_sha256: string }>; max_column: number; max_row: number; tab_id: string; title: string }> };
type Mapping = { constants: { normalization_version: string }; record_selectors: Array<{ a1_range_or_null: string; data_start_row_or_null: number; header_row_or_null: number; tab_id_or_null: string; tab_title_snapshot_or_null: string }> };
function fail(code: string): never { throw new Error(code); }
function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) fail(`missing_argument:${name}`); return process.argv[index + 1]; }
function text(value: unknown): string { return String(value ?? "").normalize("NFC").trim().replace(/\s+/g, " "); }
function sha(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function columnName(column: number): string { let value = column; let result = ""; while (value > 0) { value -= 1; result = String.fromCharCode(65 + (value % 26)) + result; value = Math.floor(value / 26); } return result; }
function tabRange(title: string, range: string): string { return `'${title.replaceAll("'", "''")}'!${range}`; }
function classification(direction: string) { return { allocation_request_uid_or_null: null, category_splits: [], classification_kind: "pending_manual_source_decision", direction, dues_year_or_null: null, event_kind: direction === "credit" ? "unclassified_credit" : "unclassified_debit", event_party_uid_or_null: null, group_roster_batch_uid_or_null: null, member_uid_or_null: null, outcome: "quarantine", party_kind: "unknown", receipt_uid_or_null: null, refund_receipt_uid_or_null: null, reverses_event_uid_or_null: null }; }

async function main() {
  const sourceCode = arg("--source") as SourceCode; const config = CONFIG[sourceCode]; if (!config) fail("bank_v3_source_invalid"); const output = arg("--output"); if (!(output.startsWith("/tmp/") || output.startsWith("/private/tmp/")) || existsSync(output)) fail("bank_v3_output_invalid");
  const profile = JSON.parse(readFileSync(config.profile, "utf8")) as Profile; const mapping = JSON.parse(readFileSync(config.mapping, "utf8")) as Mapping; const tab = profile.tabs[0]; const selector = mapping.record_selectors[0];
  const credentials = { type: "service_account", project_id: "dynamic-waters-446615-e5", private_key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"), client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL, token_uri: "https://oauth2.googleapis.com/token" }; if (!credentials.private_key || !credentials.client_email) fail("google_service_account_unavailable");
  const auth = new google.auth.GoogleAuth({ credentials, scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly", "https://www.googleapis.com/auth/drive.metadata.readonly"] }); const sheets = google.sheets({ version: "v4", auth });
  const [drive, metadata, headerResult] = await Promise.all([google.drive({ version: "v3", auth }).files.get({ fileId: SPREADSHEET_ID, fields: "version,modifiedTime" }), sheets.spreadsheets.get({ spreadsheetId: SPREADSHEET_ID, fields: "sheets(properties(sheetId,title,gridProperties(rowCount,columnCount)))" }), sheets.spreadsheets.values.get({ spreadsheetId: SPREADSHEET_ID, range: tabRange(tab.title, `A${selector.header_row_or_null}:${columnName(tab.max_column)}${selector.header_row_or_null}`), valueRenderOption: "FORMATTED_VALUE" })]);
  const revision = `drive-version:${drive.data.version};modified:${drive.data.modifiedTime}`; if (revision !== profile.source_revision) fail("bank_v3_profile_revision_stale"); const provider = (metadata.data.sheets ?? []).filter((sheet) => String(sheet.properties?.sheetId) === tab.tab_id); if (provider.length !== 1 || provider[0].properties?.title !== tab.title || provider[0].properties?.gridProperties?.rowCount !== tab.max_row || provider[0].properties?.gridProperties?.columnCount !== tab.max_column) fail("bank_v3_tab_profile_drift");
  const header = headerResult.data.values?.[0] ?? []; if (sha(header) !== tab.header_candidates[0].values_sha256) fail("bank_v3_header_profile_drift"); const positions = Object.fromEntries(config.allowed.map((name) => [name, header.flatMap((value, index) => text(value) === name ? [index + 1] : [])])); if (config.allowed.some((name) => positions[name].length !== 1)) fail("bank_v3_header_contract_mismatch");
  const endRow = selector.a1_range_or_null.match(/:(?:[A-Z]+)(\d+)$/)?.[1]; if (!endRow) fail("bank_v3_range_invalid"); const ranges = config.allowed.map((name) => tabRange(tab.title, `${columnName(positions[name][0])}${selector.data_start_row_or_null}:${columnName(positions[name][0])}${endRow}`)); const columns = (await sheets.spreadsheets.values.batchGet({ spreadsheetId: SPREADSHEET_ID, ranges, valueRenderOption: "UNFORMATTED_VALUE", dateTimeRenderOption: "SERIAL_NUMBER" })).data.valueRanges ?? [];
  const values = Object.fromEntries(config.allowed.map((name, index) => [name, (columns[index].values ?? []).map((row) => row[0] ?? null)])); const length = Math.max(0, ...Object.values(values).map((column) => column.length)); const rows: SourcePreviewInput["rows"] = [];
  for (let index = 0; index < length; index += 1) { const sourceValues = Object.fromEntries(config.allowed.map((name) => [name, values[name][index] ?? null])); if (Object.values(sourceValues).every((value) => text(value) === "")) continue; const rowNumber = selector.data_start_row_or_null + index; const coordinateKey = `sheet:${SPREADSHEET_ID}:${tab.tab_id}:row:${rowNumber}`; const payload = normalizeBankRowV3(sourceCode, { coordinateKey, values: sourceValues }); rows.push({ coordinate_key: coordinateKey, coordinate_normalization_version: "coordinate-v1", issue_status: "warning", normalization_version: mapping.constants.normalization_version, normalized_payload: payload, raw_payload: payload, source_display_snapshot: tab.title, decisions: [{ decision_kind: "classification", decision_payload: classification(payload.direction) }] }); }
  if (rows.length !== config.expectedRows) fail("bank_v3_row_coverage_mismatch"); const input: SourcePreviewInput = { schema_version: "accounting-source-preview-input-v2", source_code: sourceCode, source_uid: config.sourceUid, release_uid: config.releaseUid, source_revision: revision, source_fingerprint: "0".repeat(64), operation_uid: randomUUID(), batch_uid: randomUUID(), decision_set_uid: randomUUID(), captured_timezone: "Asia/Seoul", coverage_from: config.coverageFrom, coverage_through: config.coverageThrough, rows }; input.source_fingerprint = sourceFingerprint(input); validateSourcePreviewInput(input); writeFileSync(output, `${JSON.stringify(input)}\n`, { flag: "wx", mode: 0o600 }); chmodSync(output, 0o600); console.log(JSON.stringify({ schema_version: "bank-source-preview-input-result-v3", source_code: sourceCode, source_fingerprint: input.source_fingerprint, row_count: rows.length, quarantine_classification_count: rows.length, excluded_columns_read: 0, original_write_count: 0, output_created: true, result: "materialized" }));
}
main().catch((error) => { console.error(JSON.stringify({ schema_version: "bank-source-preview-input-error-v3", error_code: error instanceof Error ? error.message : "unknown", original_write_count: 0, output_created: false, result: "rejected" })); process.exitCode = 1; });
