import { createTargetPool, resolveDevelopmentTarget, shutdownPool, verifyDevelopmentTarget } from "../server/db-target";

function fail(code: string): never { throw new Error(code); }
function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) fail(`missing_argument:${name}`); return process.argv[index + 1]; }

async function main() {
  if (arg("--target") !== "development") fail("legacy_payments_preflight_scope_mismatch");
  const resolved = resolveDevelopmentTarget(process.env, "migration"); const pool = createTargetPool(resolved);
  try {
    const target = await verifyDevelopmentTarget(pool, resolved); const client = await pool.connect();
    try {
      await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");
      const paymentState = (await client.query<{ payment_count: number; watermark: number; null_user: number; nonpositive: number; invalid_year: number; invalid_type: number; invalid_status: number; null_created_at: number }>(`SELECT count(*)::int payment_count,coalesce(max(id),0)::int watermark,count(*) FILTER (WHERE user_id IS NULL)::int null_user,count(*) FILTER (WHERE amount<=0)::int nonpositive,count(*) FILTER (WHERE year NOT BETWEEN 2024 AND 2026)::int invalid_year,count(*) FILTER (WHERE type<>'연회비')::int invalid_type,count(*) FILTER (WHERE status<>'completed')::int invalid_status,count(*) FILTER (WHERE created_at IS NULL)::int null_created_at FROM public.payments`)).rows[0];
      const constraints = (await client.query<{ constraint_name: string; validated: boolean }>(`SELECT conname constraint_name,convalidated validated FROM pg_constraint WHERE conrelid='public.payments'::regclass AND conname=ANY($1::text[]) ORDER BY conname`, [["payments__amount_positive__check", "payments__status_domain__check", "payments__type_domain__check", "payments__year_domain__check"]])).rows;
      const expectedConstraintNames = ["payments__amount_positive__check", "payments__status_domain__check", "payments__type_domain__check", "payments__year_domain__check"];
      if (constraints.length !== 4 || constraints.some((row, index) => row.constraint_name !== expectedConstraintNames[index] || !row.validated)) fail("legacy_payments_constraint_state_mismatch");
      const sourceState = (await client.query<{ logical_sources: number; active_releases: number; batches: number; applied_batches: number; sets: number; approved_sets: number; items: number }>(`SELECT (SELECT count(*)::int FROM public.accounting_logical_sources WHERE source_code='LEGACY_PAYMENTS') logical_sources,(SELECT count(*)::int FROM public.accounting_source_releases r JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code='LEGACY_PAYMENTS' AND r.status='active') active_releases,(SELECT count(*)::int FROM public.accounting_import_batches b JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code='LEGACY_PAYMENTS') batches,(SELECT count(*)::int FROM public.accounting_import_batches b JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code='LEGACY_PAYMENTS' AND b.status='applied') applied_batches,(SELECT count(*)::int FROM public.source_decision_sets ds JOIN public.accounting_import_batches b ON b.id=ds.batch_id JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code='LEGACY_PAYMENTS') sets,(SELECT count(*)::int FROM public.source_decision_sets ds JOIN public.accounting_import_batches b ON b.id=ds.batch_id JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code='LEGACY_PAYMENTS' AND ds.status='approved') approved_sets,(SELECT count(*)::int FROM public.source_decision_items i JOIN public.source_decision_sets ds ON ds.id=i.decision_set_id JOIN public.accounting_import_batches b ON b.id=ds.batch_id JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code='LEGACY_PAYMENTS') items`)).rows[0];
      const legacyState = (await client.query<{ decisions: number; cutover_states: number; open_exceptions: number; claims: number; events: number; receipts: number; allocations: number }>(`SELECT (SELECT count(*)::int FROM public.legacy_payment_decisions) decisions,(SELECT count(*)::int FROM public.legacy_cutover_states) cutover_states,(SELECT count(*)::int FROM public.schema_data_exceptions WHERE table_name='payments' AND status='open') open_exceptions,(SELECT count(*)::int FROM public.economic_event_claims) claims,(SELECT count(*)::int FROM public.economic_events) events,(SELECT count(*)::int FROM public.dues_receipts) receipts,(SELECT count(*)::int FROM public.dues_allocations) allocations`)).rows[0];
      if (paymentState.payment_count !== 0 || paymentState.watermark !== 0 || Object.entries(paymentState).some(([key, value]) => !["payment_count", "watermark"].includes(key) && value !== 0)) fail("legacy_payments_live_rows_unexpected");
      if (sourceState.logical_sources !== 1 || sourceState.active_releases !== 1 || sourceState.batches !== 1 || sourceState.applied_batches !== 1 || sourceState.sets !== 1 || sourceState.approved_sets !== 1 || sourceState.items !== 0) fail("legacy_payments_source_state_mismatch");
      if (Object.values(legacyState).some((value) => value !== 0)) fail("legacy_payments_downstream_state_mismatch");
      await client.query("ROLLBACK");
      console.log(JSON.stringify({ schema_version: "legacy-payments-preflight-v1", target: "development", target_fingerprint: target.targetFingerprint, payment_state: paymentState, constraints_validated: constraints.length, source_state: sourceState, legacy_state: legacyState, dry_run_eligible_rows: 0, dry_run_ineligible_rows: 0, cutover_watermark_candidate: 0, pii_snapshots_output: 0, terminal_transaction: "ROLLBACK", result: "verified" }));
    } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
  } finally { await shutdownPool(pool); }
}

main().catch((error) => { console.error(JSON.stringify({ schema_version: "legacy-payments-preflight-error-v1", error_code: error instanceof Error ? error.message : "unknown", result: "rejected" })); process.exitCode = 1; });
