import { createTargetPool, resolveDevelopmentTarget, shutdownPool, verifyDevelopmentTarget } from "../server/db-target";

function fail(code: string): never { throw new Error(code); }
function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) fail(`missing_argument:${name}`); return process.argv[index + 1]; }

async function main() {
  if (arg("--target") !== "development") fail("foreign_faculty_primary_preflight_scope_mismatch");
  const resolved = resolveDevelopmentTarget(process.env, "migration"); const pool = createTargetPool(resolved);
  try {
    const target = await verifyDevelopmentTarget(pool, resolved); const client = await pool.connect();
    try {
      await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");
      const roster = (await client.query<{ batch_uid: string; decision_set_uid: string; batch_status: string; set_status: string; row_count: number; item_count: number; candidate_total: string }>(`SELECT b.batch_uid::text,s.decision_set_uid::text,b.status batch_status,s.status set_status,b.row_count,(SELECT count(*)::int FROM public.source_decision_items i WHERE i.decision_set_id=s.id) item_count,(SELECT coalesce(sum((rv.normalized_payload->>'proposed_amount')::numeric),0)::text FROM public.accounting_import_batch_rows br JOIN public.accounting_import_row_versions rv ON rv.id=br.row_version_id WHERE br.batch_id=b.id) candidate_total FROM public.accounting_import_batches b JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources ls ON ls.id=r.logical_source_id JOIN public.source_decision_sets s ON s.batch_id=b.id WHERE ls.source_code='GROUP_FOREIGN_FACULTY_2025' AND r.adapter_version='3.0.0'`)).rows;
      if (roster.length !== 1 || roster[0].row_count !== 26 || roster[0].item_count !== 52 || roster[0].candidate_total !== "1300000" || roster[0].batch_status !== "previewed" || roster[0].set_status !== "previewed") fail("foreign_faculty_roster_state_mismatch");
      const candidates = (await client.query<{ source_code: string; batch_uid: string; decision_set_uid: string; batch_status: string; set_status: string; coordinate_key: string; content_digest: string; posted_date: string; occurred_at: string; amount: string; direction: string; decision_outcome: string; payer_digest: string | null; description_digest: string | null }>(`SELECT ls.source_code,b.batch_uid::text,s.decision_set_uid::text,b.status batch_status,s.status set_status,c.coordinate_key,rv.content_digest,rv.normalized_payload->>'posted_date' posted_date,rv.normalized_payload->>'occurred_at' occurred_at,rv.normalized_payload->>'amount' amount,rv.normalized_payload->>'direction' direction,i.decision_payload->>'outcome' decision_outcome,rv.normalized_payload->>'payer_name_key_digest' payer_digest,rv.normalized_payload->>'transaction_description_digest' description_digest FROM public.accounting_import_batches b JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources ls ON ls.id=r.logical_source_id JOIN public.accounting_import_batch_rows br ON br.batch_id=b.id JOIN public.accounting_import_coordinates c ON c.id=br.coordinate_id JOIN public.accounting_import_row_versions rv ON rv.id=br.row_version_id JOIN public.source_decision_sets s ON s.batch_id=b.id JOIN public.source_decision_items i ON i.decision_set_id=s.id AND i.coordinate_id=c.id AND i.decision_kind='classification' WHERE ls.source_code IN ('BANK_TOSS_2026','BANK_IBK_2026') AND r.adapter_version='3.0.0' AND rv.normalized_payload->>'amount'='1300000' AND rv.normalized_payload->>'direction'='credit' ORDER BY ls.source_code,c.coordinate_key`)).rows;
      if (candidates.some((row) => row.decision_outcome !== "quarantine" || row.batch_status !== "applied" || row.set_status !== "approved")) fail("foreign_faculty_primary_candidate_state_mismatch");
      const ledgerCandidates = (await client.query<{ source_code: string; batch_uid: string; decision_set_uid: string; batch_status: string; set_status: string; coordinate_key: string; content_digest: string; occurred_date: string; occurred_at: string; amount: string; direction: string; decision_outcome: string; payer_digest: string | null; description_digest: string | null }>(`SELECT ls.source_code,b.batch_uid::text,s.decision_set_uid::text,b.status batch_status,s.status set_status,c.coordinate_key,rv.content_digest,rv.normalized_payload->>'occurred_date' occurred_date,rv.normalized_payload->>'occurred_at' occurred_at,rv.normalized_payload->>'amount' amount,rv.normalized_payload->>'direction' direction,i.decision_payload->>'outcome' decision_outcome,rv.normalized_payload->>'payer_digest' payer_digest,rv.normalized_payload->>'description_digest' description_digest FROM public.accounting_import_batches b JOIN public.accounting_source_releases r ON r.id=b.source_release_id JOIN public.accounting_logical_sources ls ON ls.id=r.logical_source_id JOIN public.accounting_import_batch_rows br ON br.batch_id=b.id JOIN public.accounting_import_coordinates c ON c.id=br.coordinate_id JOIN public.accounting_import_row_versions rv ON rv.id=br.row_version_id JOIN public.source_decision_sets s ON s.batch_id=b.id JOIN public.source_decision_items i ON i.decision_set_id=s.id AND i.coordinate_id=c.id AND i.decision_kind='classification' WHERE ls.source_code='LEDGER_FINAL_2022_2025' AND r.adapter_version='3.0.0' AND rv.normalized_payload->>'coordinate_kind'='economic' AND rv.normalized_payload->>'amount'='1300000' AND rv.normalized_payload->>'direction'='credit' ORDER BY c.coordinate_key`)).rows;
      if (ledgerCandidates.some((row) => row.decision_outcome !== "quarantine" || row.batch_status !== "applied" || row.set_status !== "approved")) fail("foreign_faculty_ledger_candidate_state_mismatch");
      await client.query("ROLLBACK");
      console.log(JSON.stringify({ schema_version: "foreign-faculty-primary-receipt-preflight-v1", target: "development", target_fingerprint: target.targetFingerprint, roster: roster[0], expected_primary_amount: "1300000", eligible_bank_candidate_count: candidates.length, eligible_bank_candidates: candidates, historical_ledger_candidate_count: ledgerCandidates.length, historical_ledger_candidates: ledgerCandidates, direct_group_apply_ready: false, blocking_reason: candidates.length === 0 ? ledgerCandidates.length > 0 ? "historical_ledger_candidate_is_not_an_eligible_bank_receipt" : "no_exact_source_candidate" : candidates.length > 1 ? "ambiguous_exact_bank_candidates" : "primary_bank_set_already_approved_quarantine_requires_resolution_path", pii_snapshots_output: 0, terminal_transaction: "ROLLBACK", result: "verified" }));
    } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); }
  } finally { await shutdownPool(pool); }
}

main().catch((error) => { console.error(JSON.stringify({ schema_version: "foreign-faculty-primary-receipt-preflight-error-v1", error_code: error instanceof Error ? error.message : "unknown", result: "rejected" })); process.exitCode = 1; });
