import { createHash, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import type { PoolClient } from "pg";
import { createOrResumeDisposableTarget, closeDisposableTarget, createTargetPool, resolveDisposableControlTarget, shutdownPool, verifyDevelopmentTarget } from "../server/db-target";
import { canonicalJson, sha256, type CanonicalValue } from "../server/accounting/source-contracts";
import { decideSourcePreview } from "../server/accounting/source-decision-service";
import { readSourceDecisionReview } from "../server/accounting/source-decision-review";
import { verifyActorReceipt } from "./admin-actor-receipt";

function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) throw new Error(`missing_argument:${name}`); return process.argv[index + 1]; }
function deterministicUuidV4(seed: string): string { const bytes = createHash("sha256").update(seed).digest().subarray(0, 16); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; const hex = bytes.toString("hex"); return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`; }
async function reserve(client: PoolClient, table: string): Promise<string> { return (await client.query<{ id: string }>("SELECT nextval(pg_get_serial_sequence($1,'id'))::text id", [`public.${table}`])).rows[0].id; }

async function seedPreview(client: PoolClient, runUid: string, actor: Awaited<ReturnType<typeof verifyActorReceipt>>) {
  const source = await client.query<{ source_id: string; release_id: string }>(`SELECT s.id::text source_id,r.id::text release_id FROM public.accounting_logical_sources s JOIN public.accounting_source_releases r ON r.logical_source_id=s.id WHERE s.source_code='MEMBERSHIP_INTEGRATED_ADDRESS_BOOK' AND r.adapter_version='1.0.0' AND r.status='active' FOR UPDATE OF s,r`);
  if (source.rowCount !== 1) throw new Error("task_18_disposable_seed_release_missing");
  const batchUid = deterministicUuidV4(`${runUid}\nbatch`); const setUid = deterministicUuidV4(`${runUid}\nset`); const fingerprint = sha256(`task-18-disposable:${runUid}`); const coordinateKey = `disposable:${runUid}:1`;
  const normalized = { generation: "synthetic", member_name: "synthetic-member" }; const contentDigest = sha256(canonicalJson(normalized)); const decisionPayload = { outcome: "quarantine", reason_code: "DISPOSABLE_SYNTHETIC" }; const payloadSha = sha256(canonicalJson(decisionPayload));
  const manifest = { schema_version: "source-decision-preview-v1", batch_uid: batchUid, source_fingerprint: fingerprint, items: [{ ordinal: 1, coordinate_key: coordinateKey, source_content_digest: contentDigest, decision_kind: "member_match", decision_payload_sha256: payloadSha }] }; const manifestSha = sha256(canonicalJson(manifest as CanonicalValue));
  const batchManifest = { schema_version: "accounting-source-batch-preview-v1", rows: [{ coordinate_key: coordinateKey, source_content_digest: contentDigest }] }; const batchManifestSha = sha256(canonicalJson(batchManifest as CanonicalValue));
  const now = new Date().toISOString(); const correlation = randomUUID(); const batchId = await reserve(client, "accounting_import_batches"); const coordinateId = await reserve(client, "accounting_import_coordinates"); const rowId = await reserve(client, "accounting_import_row_versions"); const linkId = await reserve(client, "accounting_import_batch_rows"); const setId = await reserve(client, "source_decision_sets"); const itemId = await reserve(client, "source_decision_items");
  await client.query(`INSERT INTO public.accounting_import_batches (id,batch_uid,captured_timezone,coverage_from,coverage_through,error_count,preview_actor_at,preview_actor_authorization_version,preview_actor_correlation_uid,preview_actor_name_snapshot,preview_actor_scope,preview_actor_uid_snapshot,preview_actor_user_id,preview_manifest,preview_manifest_sha256,previewed_at,row_count,source_fingerprint,source_release_id,source_revision,status,warning_count) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,'Asia/Seoul',$3::timestamptz,$3::timestamptz + interval '1 second',0,$3::timestamptz,$4,$5::uuid,$6,'admin',$7::uuid,$8,$9::jsonb,$10,$3::timestamptz,1,$11,$12,'disposable-synthetic','previewed',1)`, [batchId,batchUid,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,canonicalJson(batchManifest as CanonicalValue),batchManifestSha,fingerprint,source.rows[0].release_id]);
  await client.query(`INSERT INTO public.accounting_import_coordinates (id,coordinate_key,coordinate_normalization_version,logical_source_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,'disposable-v1',$3,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9)`, [coordinateId,coordinateKey,source.rows[0].source_id,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.accounting_import_row_versions (id,batch_id,content_digest,coordinate_id,issue_status,normalization_version,normalized_payload,raw_payload,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,recorded_at,source_display_snapshot,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,'warning','disposable-v1',$5::jsonb,'{}'::jsonb,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,$6::timestamptz,'synthetic',NULL,1)`, [rowId,batchId,contentDigest,coordinateId,canonicalJson(normalized),now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.accounting_import_batch_rows (id,batch_id,coordinate_id,ordinal,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,1,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9,$10)`, [linkId,batchId,coordinateId,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,rowId]);
  await client.query(`INSERT INTO public.source_decision_sets (id,batch_id,decision_set_uid,manifest,manifest_sha256,preview_actor_at,preview_actor_authorization_version,preview_actor_correlation_uid,preview_actor_name_snapshot,preview_actor_scope,preview_actor_uid_snapshot,preview_actor_user_id,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3::uuid,$4::jsonb,$5,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,'previewed')`, [setId,batchId,setUid,canonicalJson(manifest as CanonicalValue),manifestSha,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.source_decision_items (id,coordinate_id,decision_kind,decision_payload,decision_payload_sha256,decision_set_id,ordinal,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,'member_match',$3::jsonb,$4,$5,1,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,$12)`, [itemId,coordinateId,canonicalJson(decisionPayload),payloadSha,setId,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,rowId]);
  return { batchUid, setUid, fingerprint, manifestSha, coordinateKey, contentDigest, decisionPayload };
}

async function main() {
  if (arg("--target") !== "disposable-test") throw new Error("task_18_disposable_target_forbidden"); const action = arg("--action"); const runUid = arg("--run-uid"); const actorReceiptPath = arg("--actor-receipt");
  const receiptFile = JSON.parse(readFileSync(actorReceiptPath,"utf8")) as { candidate_user_id:number };
  const controlResolved = resolveDisposableControlTarget(process.env,runUid); const controlPool=createTargetPool(controlResolved); let disposable:Awaited<ReturnType<typeof createOrResumeDisposableTarget>>|undefined;
  try { const development=await verifyDevelopmentTarget(controlPool,{...controlResolved,kind:"development"}); disposable=await createOrResumeDisposableTarget(controlPool,development,runUid); const actor=await verifyActorReceipt(disposable.pool,actorReceiptPath,{kind:"disposable-test",targetFingerprint:disposable.targetFingerprint,disposableRunUid:runUid,parentTargetFingerprint:disposable.parentTargetFingerprint}); if(actor.userId!==receiptFile.candidate_user_id)throw new Error("task_18_disposable_actor_mismatch");
    const client=await disposable.pool.connect(); let seeded:Awaited<ReturnType<typeof seedPreview>>; try{await client.query("BEGIN");seeded=await seedPreview(client,runUid,actor);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
    const actorContext={userId:actor.userId,userUid:actor.userUid,name:actor.name,authorizationVersion:actor.authorizationVersion,targetFingerprint:disposable.targetFingerprint}; const reject={schemaVersion:"source-decision-command-v1",operationUid:deterministicUuidV4(`${runUid}\nreject`),manifestSha256:seeded.manifestSha,sourceFingerprint:seeded.fingerprint,decision:"reject",replacementDecisionSetUid:null,replacementManifest:null,replacementItems:null,replacementManifestSha256:null}; await decideSourcePreview(disposable.pool,seeded.setUid,reject,actorContext);
    const replacementUid=deterministicUuidV4(`${runUid}\nreplacement`); const replacementPayload={outcome:"quarantine",reason_code:"DISPOSABLE_REVIEWED"}; const replacementPayloadSha=sha256(canonicalJson(replacementPayload)); const replacementManifest={schema_version:"source-decision-preview-v1",batch_uid:seeded.batchUid,source_fingerprint:seeded.fingerprint,items:[{ordinal:1,coordinate_key:seeded.coordinateKey,source_content_digest:seeded.contentDigest,decision_kind:"member_match",decision_payload_sha256:replacementPayloadSha}]}; const repreview={...reject,operationUid:deterministicUuidV4(`${runUid}\nrepreview`),decision:"repreview",replacementDecisionSetUid:replacementUid,replacementManifest,replacementItems:[{ordinal:1,decisionPayload:replacementPayload,decisionPayloadSha256:replacementPayloadSha}],replacementManifestSha256:sha256(canonicalJson(replacementManifest as CanonicalValue))};
    if(action==="failure"){const before=await disposable.pool.query<{sets:number;items:number;receipts:number}>("SELECT (SELECT count(*)::int FROM public.source_decision_sets) sets,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts");let code="";try{await decideSourcePreview(disposable.pool,seeded.setUid,{...repreview,replacementItems:[]},actorContext);}catch(error){code=error instanceof Error?error.message:"unknown";}const after=await disposable.pool.query<{sets:number;items:number;receipts:number}>("SELECT (SELECT count(*)::int FROM public.source_decision_sets) sets,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts");if(!code.includes("item_coverage_mismatch")||canonicalJson(before.rows[0] as never)!==canonicalJson(after.rows[0] as never))throw new Error("task_18_disposable_failure_state_changed");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-repreview-v1",case:"failure",error_code:"source_decision_item_coverage_mismatch",state_identical:true,result:"rejected"}));process.exitCode=1;return;}
    if(action!=="happy")throw new Error("task_18_disposable_action_invalid");const first=await decideSourcePreview(disposable.pool,seeded.setUid,repreview,actorContext);const replay=await decideSourcePreview(disposable.pool,seeded.setUid,repreview,actorContext);const review=await readSourceDecisionReview(disposable.pool,replacementUid);const counts=(await disposable.pool.query<{old_rejected:number;fresh_previewed:number;batches_previewed:number;items:number;receipts:number;downstream:number}>(`SELECT (SELECT count(*)::int FROM public.source_decision_sets WHERE decision_set_uid=$1::uuid AND status='rejected') old_rejected,(SELECT count(*)::int FROM public.source_decision_sets WHERE decision_set_uid=$2::uuid AND status='previewed') fresh_previewed,(SELECT count(*)::int FROM public.accounting_import_batches WHERE batch_uid=$3::uuid AND status='previewed') batches_previewed,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts,((SELECT count(*) FROM public.source_row_classification_decisions)+(SELECT count(*) FROM public.member_match_cases)+(SELECT count(*) FROM public.member_position_assignments)+(SELECT count(*) FROM public.economic_events))::int downstream`,[seeded.setUid,replacementUid,seeded.batchUid])).rows[0];if(first.receipt_sha256!==replay.receipt_sha256||review?.status!=="previewed"||review.items.length!==1||counts.old_rejected!==1||counts.fresh_previewed!==1||counts.batches_previewed!==1||counts.items!==2||counts.receipts!==2||counts.downstream!==0)throw new Error("task_18_disposable_happy_mismatch");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-repreview-v1",case:"happy",reject_repreview:true,repreview_verified_noop:true,fresh_get_verified:true,batch_reused:true,decision_set_count:2,decision_item_count:2,operation_receipt_count:2,downstream_rows:0,result:"approved"}));
  }finally{if(disposable)await closeDisposableTarget(controlPool,disposable);await shutdownPool(controlPool);}
}
main().catch((error)=>{console.error(JSON.stringify({schema_version:"dgkma-task18-disposable-repreview-error-v1",error_code:error instanceof Error?error.message:"unknown",result:"rejected"}));process.exitCode=1;});
