import { createHash, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import type { PoolClient } from "pg";
import { createOrResumeDisposableTarget, createTargetPool, resolveDisposableControlTarget, shutdownPool, teardownDisposableTarget, verifyDevelopmentTarget } from "../server/db-target";
import { canonicalJson, sha256, type CanonicalValue } from "../server/accounting/source-contracts";
import { decideSourcePreview } from "../server/accounting/source-decision-service";
import { readSourceDecisionReview } from "../server/accounting/source-decision-review";
import { verifyActorReceipt } from "./admin-actor-receipt";

function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) throw new Error(`missing_argument:${name}`); return process.argv[index + 1]; }
function deterministicUuidV4(seed: string): string { const bytes = createHash("sha256").update(seed).digest().subarray(0, 16); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; const hex = bytes.toString("hex"); return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`; }
async function reserve(client: PoolClient, table: string): Promise<string> { return (await client.query<{ id: string }>("SELECT nextval(pg_get_serial_sequence($1,'id'))::text id", [`public.${table}`])).rows[0].id; }

async function seedPreview(client: PoolClient, runUid: string, actor: Awaited<ReturnType<typeof verifyActorReceipt>>, mode: "quarantine"|"period") {
  const sourceCode=mode==="period"?"AGM36_PERIOD_BOUNDARY":"MEMBERSHIP_INTEGRATED_ADDRESS_BOOK";const sourceRow=await client.query<{source_id:string}>("SELECT id::text source_id FROM public.accounting_logical_sources WHERE source_code=$1 FOR UPDATE",[sourceCode]);if(sourceRow.rowCount!==1)throw new Error("task_18_disposable_seed_source_missing");let release=await client.query<{release_id:string}>("SELECT id::text release_id FROM public.accounting_source_releases WHERE logical_source_id=$1 AND status='active' ORDER BY released_at DESC,id DESC LIMIT 1 FOR UPDATE",[sourceRow.rows[0].source_id]);
  if(release.rowCount===0&&mode==="period"){const releaseId=await reserve(client,"accounting_source_releases");const now=new Date().toISOString();await client.query(`INSERT INTO public.accounting_source_releases (id,release_uid,logical_source_id,adapter_code,adapter_version,normalized_schema_sha256,normalization_implementation_sha256,mapping_table_sha256,mapping_approval_receipt_sha256,released_at,status,recorded_actor_user_id,recorded_actor_uid_snapshot,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_at,recorded_actor_correlation_uid,recorded_actor_authorization_version) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,$3,'disposable-period-v1','1.0.0',$4,$4,$4,$4,$5::timestamptz,'active',$6,$7::uuid,$8,'admin',$5::timestamptz,$9::uuid,$10)`,[releaseId,deterministicUuidV4(`${runUid}\nrelease`),sourceRow.rows[0].source_id,"a".repeat(64),now,actor.userId,actor.userUid,actor.name,randomUUID(),actor.authorizationVersion]);release={rowCount:1,rows:[{release_id:releaseId}]} as never;}
  if (release.rowCount !== 1) throw new Error("task_18_disposable_seed_release_missing");const source={rows:[{source_id:sourceRow.rows[0].source_id,release_id:release.rows[0].release_id}]};
  const batchUid = deterministicUuidV4(`${runUid}\nbatch`); const setUid = deterministicUuidV4(`${runUid}\nset`); const fingerprint = sha256(`task-18-disposable:${runUid}`); const coordinateKey = `disposable:${runUid}:1`;
  const boundaryDigest="b".repeat(64);const normalized=mode==="period"?{boundary_content_digest:boundaryDigest,boundary_coordinate_key:coordinateKey,boundary_source_code:sourceCode,ends_at:"2027-01-01T00:00:00+09:00",period_code:"DISPOSABLE_2026",starts_at:"2026-01-01T00:00:00+09:00"}:{generation:"synthetic",member_name:"synthetic-member"};const contentDigest=sha256(canonicalJson(normalized));const decisionKind=mode==="period"?"period_materialization":"member_match";const decisionPayload=mode==="period"?{...normalized,outcome:"approve"}:{candidate_member_uid_or_null:null,case_uid:deterministicUuidV4(`${runUid}\ncase`),evidence_digest:sha256(`${runUid}\nevidence`),evidence_kind:"name_only",outcome:"quarantine",score_basis:"name_only_unapprovable"};const payloadSha=sha256(canonicalJson(decisionPayload));
  const manifest = { schema_version: "source-decision-preview-v1", batch_uid: batchUid, source_fingerprint: fingerprint, items: [{ ordinal: 1, coordinate_key: coordinateKey, source_content_digest: contentDigest, decision_kind: decisionKind, decision_payload_sha256: payloadSha }] }; const manifestSha = sha256(canonicalJson(manifest as CanonicalValue));
  const batchManifest = { schema_version: "accounting-source-batch-preview-v1", rows: [{ coordinate_key: coordinateKey, source_content_digest: contentDigest }] }; const batchManifestSha = sha256(canonicalJson(batchManifest as CanonicalValue));
  const now = new Date().toISOString(); const correlation = randomUUID(); const batchId = await reserve(client, "accounting_import_batches"); const coordinateId = await reserve(client, "accounting_import_coordinates"); const rowId = await reserve(client, "accounting_import_row_versions"); const linkId = await reserve(client, "accounting_import_batch_rows"); const setId = await reserve(client, "source_decision_sets"); const itemId = await reserve(client, "source_decision_items");
  await client.query(`INSERT INTO public.accounting_import_batches (id,batch_uid,captured_timezone,coverage_from,coverage_through,error_count,preview_actor_at,preview_actor_authorization_version,preview_actor_correlation_uid,preview_actor_name_snapshot,preview_actor_scope,preview_actor_uid_snapshot,preview_actor_user_id,preview_manifest,preview_manifest_sha256,previewed_at,row_count,source_fingerprint,source_release_id,source_revision,status,warning_count) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,'Asia/Seoul',$3::timestamptz,$3::timestamptz + interval '1 second',0,$3::timestamptz,$4,$5::uuid,$6,'admin',$7::uuid,$8,$9::jsonb,$10,$3::timestamptz,1,$11,$12,'disposable-synthetic','previewed',1)`, [batchId,batchUid,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,canonicalJson(batchManifest as CanonicalValue),batchManifestSha,fingerprint,source.rows[0].release_id]);
  await client.query(`INSERT INTO public.accounting_import_coordinates (id,coordinate_key,coordinate_normalization_version,logical_source_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,'disposable-v1',$3,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9)`, [coordinateId,coordinateKey,source.rows[0].source_id,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.accounting_import_row_versions (id,batch_id,content_digest,coordinate_id,issue_status,normalization_version,normalized_payload,raw_payload,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,recorded_at,source_display_snapshot,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,'warning','disposable-v1',$5::jsonb,'{}'::jsonb,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,$6::timestamptz,'synthetic',NULL,1)`, [rowId,batchId,contentDigest,coordinateId,canonicalJson(normalized),now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.accounting_import_batch_rows (id,batch_id,coordinate_id,ordinal,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,1,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9,$10)`, [linkId,batchId,coordinateId,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,rowId]);
  await client.query(`INSERT INTO public.source_decision_sets (id,batch_id,decision_set_uid,manifest,manifest_sha256,preview_actor_at,preview_actor_authorization_version,preview_actor_correlation_uid,preview_actor_name_snapshot,preview_actor_scope,preview_actor_uid_snapshot,preview_actor_user_id,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3::uuid,$4::jsonb,$5,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,'previewed')`, [setId,batchId,setUid,canonicalJson(manifest as CanonicalValue),manifestSha,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.source_decision_items (id,coordinate_id,decision_kind,decision_payload,decision_payload_sha256,decision_set_id,ordinal,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4::jsonb,$5,$6,1,$7::timestamptz,$8,$9::uuid,$10,'admin',$11::uuid,$12,$13)`, [itemId,coordinateId,decisionKind,canonicalJson(decisionPayload),payloadSha,setId,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,rowId]);
  return { batchUid, setUid, fingerprint, manifestSha, coordinateKey, contentDigest, decisionPayload };
}

type DisposableActor = Awaited<ReturnType<typeof verifyActorReceipt>>;
type GroupSeedItem = { decisionKind: "classification"|"group_allocation"|"member_match"; decisionPayload: Record<string, CanonicalValue> };

async function ensureDisposableRelease(client: PoolClient, runUid: string, actor: DisposableActor, sourceCode: "BANK_TOSS_2026"|"GROUP_FOREIGN_FACULTY_2025") {
  const source = await client.query<{ source_id: string }>("SELECT id::text source_id FROM public.accounting_logical_sources WHERE source_code=$1 FOR UPDATE", [sourceCode]);
  if (source.rowCount !== 1) throw new Error("task_18_group_source_missing");
  let release = await client.query<{ release_id: string }>("SELECT id::text release_id FROM public.accounting_source_releases WHERE logical_source_id=$1 AND status='active' ORDER BY released_at DESC,id DESC LIMIT 1 FOR UPDATE", [source.rows[0].source_id]);
  if (release.rowCount === 0) {
    const releaseId = await reserve(client, "accounting_source_releases"); const now = new Date().toISOString(); const digest = sha256(`task-18-group-release:${sourceCode}`);
    await client.query(`INSERT INTO public.accounting_source_releases (id,release_uid,logical_source_id,adapter_code,adapter_version,normalized_schema_sha256,normalization_implementation_sha256,mapping_table_sha256,mapping_approval_receipt_sha256,released_at,status,recorded_actor_user_id,recorded_actor_uid_snapshot,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_at,recorded_actor_correlation_uid,recorded_actor_authorization_version) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,$3,$4,'3.0.0',$5,$5,$5,$5,$6::timestamptz,'active',$7,$8::uuid,$9,'admin',$6::timestamptz,$10::uuid,$11)`, [releaseId,deterministicUuidV4(`${runUid}\nrelease\n${sourceCode}`),source.rows[0].source_id,`disposable-${sourceCode.toLowerCase()}-v1`,digest,now,actor.userId,actor.userUid,actor.name,randomUUID(),actor.authorizationVersion]);
    release = { rowCount: 1, rows: [{ release_id: releaseId }] } as never;
  }
  if (release.rowCount !== 1) throw new Error("task_18_group_release_ambiguous");
  return { sourceId: source.rows[0].source_id, releaseId: release.rows[0].release_id };
}

async function insertDisposableGroupGraph(client: PoolClient, runUid: string, actor: DisposableActor, input: { sourceCode:"BANK_TOSS_2026"|"GROUP_FOREIGN_FACULTY_2025"; batchUid:string; setUid:string; coordinateKey:string; normalizedPayload:Record<string,CanonicalValue>; items:GroupSeedItem[] }) {
  const source = await ensureDisposableRelease(client, runUid, actor, input.sourceCode); const now = new Date().toISOString(); const correlation = randomUUID();
  const fingerprint = sha256(`task-18-group:${runUid}:${input.sourceCode}`); const contentDigest = sha256(canonicalJson(input.normalizedPayload));
  const orderedItems = [...input.items].sort((left,right)=>Buffer.compare(Buffer.from(`${input.coordinateKey}\u0000${left.decisionKind}`),Buffer.from(`${input.coordinateKey}\u0000${right.decisionKind}`))).map((item,index)=>({ ...item, ordinal:index+1, payloadSha:sha256(canonicalJson(item.decisionPayload)) }));
  const manifest = { schema_version:"source-decision-preview-v1", batch_uid:input.batchUid, source_fingerprint:fingerprint, items:orderedItems.map((item)=>({ ordinal:item.ordinal, coordinate_key:input.coordinateKey, source_content_digest:contentDigest, decision_kind:item.decisionKind, decision_payload_sha256:item.payloadSha })) }; const manifestSha=sha256(canonicalJson(manifest as CanonicalValue));
  const batchManifest={schema_version:"accounting-source-batch-preview-v1",rows:[{coordinate_key:input.coordinateKey,source_content_digest:contentDigest}]}; const batchId=await reserve(client,"accounting_import_batches");const coordinateId=await reserve(client,"accounting_import_coordinates");const rowId=await reserve(client,"accounting_import_row_versions");const linkId=await reserve(client,"accounting_import_batch_rows");const setId=await reserve(client,"source_decision_sets");
  await client.query(`INSERT INTO public.accounting_import_batches (id,batch_uid,captured_timezone,coverage_from,coverage_through,error_count,preview_actor_at,preview_actor_authorization_version,preview_actor_correlation_uid,preview_actor_name_snapshot,preview_actor_scope,preview_actor_uid_snapshot,preview_actor_user_id,preview_manifest,preview_manifest_sha256,previewed_at,row_count,source_fingerprint,source_release_id,source_revision,status,warning_count) OVERRIDING SYSTEM VALUE VALUES ($1,$2::uuid,'Asia/Seoul',$3::timestamptz,$3::timestamptz + interval '1 second',0,$3::timestamptz,$4,$5::uuid,$6,'admin',$7::uuid,$8,$9::jsonb,$10,$3::timestamptz,1,$11,$12,'disposable-group-synthetic','previewed',0)`,[batchId,input.batchUid,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,canonicalJson(batchManifest as CanonicalValue),sha256(canonicalJson(batchManifest as CanonicalValue)),fingerprint,source.releaseId]);
  await client.query(`INSERT INTO public.accounting_import_coordinates (id,coordinate_key,coordinate_normalization_version,logical_source_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,'disposable-group-v1',$3,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9)`,[coordinateId,input.coordinateKey,source.sourceId,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.accounting_import_row_versions (id,batch_id,content_digest,coordinate_id,issue_status,normalization_version,normalized_payload,raw_payload,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,recorded_at,source_display_snapshot,supersedes_id,version) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4,'accepted','disposable-group-v1',$5::jsonb,'{}'::jsonb,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,$6::timestamptz,'synthetic group preflight',NULL,1)`,[rowId,batchId,contentDigest,coordinateId,canonicalJson(input.normalizedPayload),now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  await client.query(`INSERT INTO public.accounting_import_batch_rows (id,batch_id,coordinate_id,ordinal,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,1,$4::timestamptz,$5,$6::uuid,$7,'admin',$8::uuid,$9,$10)`,[linkId,batchId,coordinateId,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,rowId]);
  await client.query(`INSERT INTO public.source_decision_sets (id,batch_id,decision_set_uid,manifest,manifest_sha256,preview_actor_at,preview_actor_authorization_version,preview_actor_correlation_uid,preview_actor_name_snapshot,preview_actor_scope,preview_actor_uid_snapshot,preview_actor_user_id,status) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3::uuid,$4::jsonb,$5,$6::timestamptz,$7,$8::uuid,$9,'admin',$10::uuid,$11,'previewed')`,[setId,batchId,input.setUid,canonicalJson(manifest as CanonicalValue),manifestSha,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId]);
  for(const item of orderedItems){const itemId=await reserve(client,"source_decision_items");await client.query(`INSERT INTO public.source_decision_items (id,coordinate_id,decision_kind,decision_payload,decision_payload_sha256,decision_set_id,ordinal,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,source_row_version_id) OVERRIDING SYSTEM VALUE VALUES ($1,$2,$3,$4::jsonb,$5,$6,$7,$8::timestamptz,$9,$10::uuid,$11,'admin',$12::uuid,$13,$14)`,[itemId,coordinateId,item.decisionKind,canonicalJson(item.decisionPayload),item.payloadSha,setId,item.ordinal,now,actor.authorizationVersion,correlation,actor.name,actor.userUid,actor.userId,rowId]);}
  return { batchUid:input.batchUid,setUid:input.setUid,fingerprint,manifestSha };
}

async function seedGroupPreflight(client: PoolClient, runUid: string, actor: DisposableActor) {
  const primaryBatchUid=deterministicUuidV4(`${runUid}\ngroup-primary-batch`);const rosterBatchUid=deterministicUuidV4(`${runUid}\ngroup-roster-batch`);const primarySetUid=deterministicUuidV4(`${runUid}\ngroup-primary-set`);const rosterSetUid=deterministicUuidV4(`${runUid}\ngroup-roster-set`);const receiptUid=deterministicUuidV4(`${runUid}\ngroup-receipt`);const memberUid=deterministicUuidV4(`${runUid}\ngroup-member`);const primaryCoordinate="bank:toss:disposable:1";const rosterCoordinate="roster:foreign-faculty:disposable:1";
  const roster=await insertDisposableGroupGraph(client,runUid,actor,{sourceCode:"GROUP_FOREIGN_FACULTY_2025",batchUid:rosterBatchUid,setUid:rosterSetUid,coordinateKey:rosterCoordinate,normalizedPayload:{generation:1,group_key_digest:sha256("synthetic-group"),group_name_snapshot:"synthetic group",member_name_key_digest:sha256("synthetic-member"),member_name_snapshot:"synthetic member",proposed_amount:"50000"},items:[{decisionKind:"group_allocation",decisionPayload:{allocation_kind_or_null:"dues",allocation_request_uid_or_null:deterministicUuidV4(`${runUid}\nallocation-request`),amount_or_null:"50000",assessment_uid_or_null:null,dues_year_or_null:2025,group_member_uid_or_null:deterministicUuidV4(`${runUid}\ngroup-member-row`),member_uid_or_null:memberUid,outcome:"approve",primary_bank_batch_uid_or_null:primaryBatchUid,primary_bank_coordinate_key_or_null:primaryCoordinate,receipt_uid_or_null:receiptUid}},{decisionKind:"member_match",decisionPayload:{candidate_member_uid_or_null:memberUid,case_uid:deterministicUuidV4(`${runUid}\nmatch-case`),evidence_digest:sha256(`${runUid}\nmatch-evidence`),evidence_kind:"roster_member_uid",outcome:"approve",score_basis:"exact_roster_member_uid"}}]});
  const primary=await insertDisposableGroupGraph(client,runUid,actor,{sourceCode:"BANK_TOSS_2026",batchUid:primaryBatchUid,setUid:primarySetUid,coordinateKey:primaryCoordinate,normalizedPayload:{amount:"50000",balance_after:"50000",direction:"credit",occurred_at:"2026-01-01T00:00:00+09:00",payer_name_key_digest:sha256("synthetic-payer"),payer_name_snapshot:"synthetic payer",posted_date:"2026-01-01",provider_row_id:"disposable:1",transaction_description_digest:sha256("synthetic-description"),transaction_description_snapshot:"synthetic dues"},items:[{decisionKind:"classification",decisionPayload:{allocation_request_uid_or_null:null,category_splits:[{amount:"50000",category_code:"DUES_INCOME"}],classification_kind:"dues",direction:"credit",dues_year_or_null:2025,event_kind:"bank",event_party_uid_or_null:null,group_roster_batch_uid_or_null:rosterBatchUid,member_uid_or_null:null,outcome:"approve",party_kind:"group",receipt_uid_or_null:receiptUid,refund_receipt_uid_or_null:null,reverses_event_uid_or_null:null}}]});
  return {primary,roster};
}

async function main() {
  if (arg("--target") !== "disposable-test") throw new Error("task_18_disposable_target_forbidden"); const action = arg("--action"); const runUid = arg("--run-uid"); const actorReceiptPath = arg("--actor-receipt");
  const receiptFile = JSON.parse(readFileSync(actorReceiptPath,"utf8")) as { candidate_user_id:number };
  const controlResolved = resolveDisposableControlTarget(process.env,runUid); const controlPool=createTargetPool(controlResolved); let disposable:Awaited<ReturnType<typeof createOrResumeDisposableTarget>>|undefined;
  try { const development=await verifyDevelopmentTarget(controlPool,{...controlResolved,kind:"development"}); disposable=await createOrResumeDisposableTarget(controlPool,development,runUid); const actor=await verifyActorReceipt(disposable.pool,actorReceiptPath,{kind:"disposable-test",targetFingerprint:disposable.targetFingerprint,disposableRunUid:runUid,parentTargetFingerprint:disposable.parentTargetFingerprint}); if(actor.userId!==receiptFile.candidate_user_id)throw new Error("task_18_disposable_actor_mismatch");
    const actorContext={userId:actor.userId,userUid:actor.userUid,name:actor.name,authorizationVersion:actor.authorizationVersion,targetFingerprint:disposable.targetFingerprint};
    if(action==="group-preflight"){
      const client=await disposable.pool.connect();let group:Awaited<ReturnType<typeof seedGroupPreflight>>;try{await client.query("BEGIN");group=await seedGroupPreflight(client,runUid,actor);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
      const stateSql=`SELECT (SELECT count(*)::int FROM public.business_operation_receipts) receipts,(SELECT count(*)::int FROM public.accounting_audit_events) audits,(SELECT count(*)::int FROM public.source_decision_sets WHERE status<>'previewed') decided_sets,(SELECT count(*)::int FROM public.accounting_import_batches WHERE status<>'previewed') applied_batches,((SELECT count(*) FROM public.source_row_classification_decisions)+(SELECT count(*) FROM public.member_match_cases)+(SELECT count(*) FROM public.member_match_candidates)+(SELECT count(*) FROM public.economic_events)+(SELECT count(*) FROM public.dues_receipts)+(SELECT count(*) FROM public.dues_allocations))::int downstream,(SELECT jsonb_agg(jsonb_build_object('sequence_name',sequencename,'last_value',last_value) ORDER BY sequencename) FROM pg_sequences WHERE schemaname='public') identity_sequences`;
      const before=(await disposable.pool.query<Record<string,CanonicalValue>>(stateSql)).rows[0];const approve={schemaVersion:"source-decision-command-v1",manifestSha256:group.primary.manifestSha,sourceFingerprint:group.primary.fingerprint,operationUid:deterministicUuidV4(`${runUid}\ngroup-approve`),decision:"approve",replacementDecisionSetUid:null,replacementManifest:null,replacementItems:null,replacementManifestSha256:null};let code="";try{await decideSourcePreview(disposable.pool,group.primary.setUid,approve,actorContext);}catch(error){code=error instanceof Error?error.message:"unknown";}const after=(await disposable.pool.query<Record<string,CanonicalValue>>(stateSql)).rows[0];if(code!=="source_decision_group_materialization_not_implemented"||canonicalJson(before)!==canonicalJson(after))throw new Error("task_18_disposable_group_preflight_mismatch");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-group-preflight-v1",primary_batch_uid:group.primary.batchUid,companion_batch_uid:group.roster.batchUid,companion_discovered_and_locked:true,manifest_and_coverage_verified:true,allocation_total_verified:"50000",identity_sequences_identical:true,error_code:code,state_identical:true,result:"rejected"}));return;
    }
    const client=await disposable.pool.connect(); let seeded:Awaited<ReturnType<typeof seedPreview>>; try{await client.query("BEGIN");seeded=await seedPreview(client,runUid,actor,action==="period"?"period":"quarantine");await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
    const base={schemaVersion:"source-decision-command-v1",manifestSha256:seeded.manifestSha,sourceFingerprint:seeded.fingerprint,replacementDecisionSetUid:null,replacementManifest:null,replacementItems:null,replacementManifestSha256:null};if(action==="period"){const approve={...base,operationUid:deterministicUuidV4(`${runUid}\nperiod-approve`),decision:"approve"};const first=await decideSourcePreview(disposable.pool,seeded.setUid,approve,actorContext);const replay=await decideSourcePreview(disposable.pool,seeded.setUid,approve,actorContext);const counts=(await disposable.pool.query<{periods:number;applied:number;receipts:number}>("SELECT (SELECT count(*)::int FROM public.accounting_periods WHERE period_code='DISPOSABLE_2026') periods,(SELECT count(*)::int FROM public.accounting_import_batches WHERE batch_uid=$1::uuid AND status='applied') applied,(SELECT count(*)::int FROM public.business_operation_receipts) receipts",[seeded.batchUid])).rows[0];if(first.receipt_sha256!==replay.receipt_sha256||counts.periods!==1||counts.applied!==1||counts.receipts!==1)throw new Error("task_18_disposable_period_mismatch");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-period-v1",period_created:1,batch_applied:1,approve_verified_noop:true,result:"approved"}));return;}
    if(action==="supersede"){
      const approve={...base,operationUid:deterministicUuidV4(`${runUid}\napprove-before-supersede`),decision:"approve"};await decideSourcePreview(disposable.pool,seeded.setUid,approve,actorContext);
      const replacementUid=deterministicUuidV4(`${runUid}\nsupersede-replacement`);const replacementPayload={candidate_member_uid_or_null:null,case_uid:deterministicUuidV4(`${runUid}\nsupersede-case`),evidence_digest:sha256(`${runUid}\nsupersede-evidence`),evidence_kind:"name_only",outcome:"quarantine",score_basis:"name_only_unapprovable"};const replacementPayloadSha=sha256(canonicalJson(replacementPayload));const replacementManifest={schema_version:"source-decision-preview-v1",batch_uid:seeded.batchUid,source_fingerprint:seeded.fingerprint,items:[{ordinal:1,coordinate_key:seeded.coordinateKey,source_content_digest:seeded.contentDigest,decision_kind:"member_match",decision_payload_sha256:replacementPayloadSha}]};const supersede={...base,operationUid:deterministicUuidV4(`${runUid}\nsupersede`),decision:"supersede",replacementDecisionSetUid:replacementUid,replacementManifest,replacementItems:[{ordinal:1,coordinateKey:seeded.coordinateKey,sourceContentDigest:seeded.contentDigest,decisionKind:"member_match",decisionPayload:replacementPayload,decisionPayloadSha256:replacementPayloadSha}],replacementManifestSha256:sha256(canonicalJson(replacementManifest as CanonicalValue))};
      const first=await decideSourcePreview(disposable.pool,seeded.setUid,supersede,actorContext);const replay=await decideSourcePreview(disposable.pool,seeded.setUid,supersede,actorContext);const review=await readSourceDecisionReview(disposable.pool,replacementUid);const counts=(await disposable.pool.query<{old_superseded:number;fresh_approved:number;batches_applied:number;items:number;receipts:number;downstream:number}>(`SELECT (SELECT count(*)::int FROM public.source_decision_sets WHERE decision_set_uid=$1::uuid AND status='superseded') old_superseded,(SELECT count(*)::int FROM public.source_decision_sets WHERE decision_set_uid=$2::uuid AND status='approved') fresh_approved,(SELECT count(*)::int FROM public.accounting_import_batches WHERE batch_uid=$3::uuid AND status='applied') batches_applied,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts,((SELECT count(*) FROM public.source_row_classification_decisions)+(SELECT count(*) FROM public.member_match_cases)+(SELECT count(*) FROM public.member_position_assignments)+(SELECT count(*) FROM public.economic_events))::int downstream`,[seeded.setUid,replacementUid,seeded.batchUid])).rows[0];
      if(first.receipt_sha256!==replay.receipt_sha256||review?.status!=="approved"||first.approved_decision_set_uids[0]!==replacementUid||first.applied_batch_uids.length!==0||counts.old_superseded!==1||counts.fresh_approved!==1||counts.batches_applied!==1||counts.items!==2||counts.receipts!==2||counts.downstream!==0)throw new Error("task_18_disposable_supersede_mismatch");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-supersede-v1",old_superseded:1,fresh_approved:1,batch_reused:true,operation_receipt_count:2,downstream_rows:0,supersede_verified_noop:true,result:"approved"}));return;
    }
    const reject={...base,operationUid:deterministicUuidV4(`${runUid}\nreject`),decision:"reject"}; await decideSourcePreview(disposable.pool,seeded.setUid,reject,actorContext);
    const replacementUid=deterministicUuidV4(`${runUid}\nreplacement`); const replacementPayload={candidate_member_uid_or_null:null,case_uid:deterministicUuidV4(`${runUid}\nreplacement-case`),evidence_digest:sha256(`${runUid}\nreplacement-evidence`),evidence_kind:"name_only",outcome:"quarantine",score_basis:"name_only_unapprovable"}; const replacementPayloadSha=sha256(canonicalJson(replacementPayload)); const replacementManifest={schema_version:"source-decision-preview-v1",batch_uid:seeded.batchUid,source_fingerprint:seeded.fingerprint,items:[{ordinal:1,coordinate_key:seeded.coordinateKey,source_content_digest:seeded.contentDigest,decision_kind:"member_match",decision_payload_sha256:replacementPayloadSha}]}; const repreview={...reject,operationUid:deterministicUuidV4(`${runUid}\nrepreview`),decision:"repreview",replacementDecisionSetUid:replacementUid,replacementManifest,replacementItems:[{ordinal:1,coordinateKey:seeded.coordinateKey,sourceContentDigest:seeded.contentDigest,decisionKind:"member_match",decisionPayload:replacementPayload,decisionPayloadSha256:replacementPayloadSha}],replacementManifestSha256:sha256(canonicalJson(replacementManifest as CanonicalValue))};
    if(action==="failure"){const before=await disposable.pool.query<{sets:number;items:number;receipts:number}>("SELECT (SELECT count(*)::int FROM public.source_decision_sets) sets,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts");let code="";try{await decideSourcePreview(disposable.pool,seeded.setUid,{...repreview,replacementItems:[]},actorContext);}catch(error){code=error instanceof Error?error.message:"unknown";}const after=await disposable.pool.query<{sets:number;items:number;receipts:number}>("SELECT (SELECT count(*)::int FROM public.source_decision_sets) sets,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts");if(!code.includes("item_coverage_mismatch")||canonicalJson(before.rows[0] as never)!==canonicalJson(after.rows[0] as never))throw new Error("task_18_disposable_failure_state_changed");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-repreview-v1",case:"failure",error_code:"source_decision_item_coverage_mismatch",state_identical:true,result:"rejected"}));process.exitCode=1;return;}
    if(action!=="happy")throw new Error("task_18_disposable_action_invalid");const first=await decideSourcePreview(disposable.pool,seeded.setUid,repreview,actorContext);const replay=await decideSourcePreview(disposable.pool,seeded.setUid,repreview,actorContext);const review=await readSourceDecisionReview(disposable.pool,replacementUid);if(first.receipt_sha256!==replay.receipt_sha256||review?.status!=="previewed"||review.items.length!==1)throw new Error("task_18_disposable_fresh_review_mismatch");const approve={...reject,operationUid:deterministicUuidV4(`${runUid}\napprove`),manifestSha256:String(repreview.replacementManifestSha256),decision:"approve"};const approved=await decideSourcePreview(disposable.pool,replacementUid,approve,actorContext);const approveReplay=await decideSourcePreview(disposable.pool,replacementUid,approve,actorContext);const counts=(await disposable.pool.query<{old_rejected:number;fresh_approved:number;batches_applied:number;items:number;receipts:number;downstream:number}>(`SELECT (SELECT count(*)::int FROM public.source_decision_sets WHERE decision_set_uid=$1::uuid AND status='rejected') old_rejected,(SELECT count(*)::int FROM public.source_decision_sets WHERE decision_set_uid=$2::uuid AND status='approved') fresh_approved,(SELECT count(*)::int FROM public.accounting_import_batches WHERE batch_uid=$3::uuid AND status='applied') batches_applied,(SELECT count(*)::int FROM public.source_decision_items) items,(SELECT count(*)::int FROM public.business_operation_receipts) receipts,((SELECT count(*) FROM public.source_row_classification_decisions)+(SELECT count(*) FROM public.member_match_cases)+(SELECT count(*) FROM public.member_position_assignments)+(SELECT count(*) FROM public.economic_events))::int downstream`,[seeded.setUid,replacementUid,seeded.batchUid])).rows[0];if(approved.receipt_sha256!==approveReplay.receipt_sha256||approved.applied_batch_uids[0]!==seeded.batchUid||approved.approved_decision_set_uids[0]!==replacementUid||counts.old_rejected!==1||counts.fresh_approved!==1||counts.batches_applied!==1||counts.items!==2||counts.receipts!==3||counts.downstream!==0)throw new Error("task_18_disposable_happy_mismatch");console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-repreview-v1",case:"happy",reject_repreview_approve:true,repreview_verified_noop:true,approve_verified_noop:true,fresh_get_verified:true,batch_reused:true,decision_set_count:2,decision_item_count:2,operation_receipt_count:3,downstream_rows:0,result:"approved"}));
  }finally{if(disposable){const teardown=await teardownDisposableTarget(controlPool,disposable);console.log(JSON.stringify({schema_version:"dgkma-task18-disposable-teardown-v1",...teardown,result:"approved"}));}await shutdownPool(controlPool);}
}
main().catch((error)=>{console.error(JSON.stringify({schema_version:"dgkma-task18-disposable-repreview-error-v1",error_code:error instanceof Error?error.message:"unknown",result:"rejected"}));process.exitCode=1;});
