import { readFileSync } from "node:fs";
import type { PoolClient } from "pg";
import { createTargetPool, resolveDevelopmentTarget, shutdownPool, verifyDevelopmentTarget } from "../server/db-target";
import { batchPreviewManifest, buildDecisionManifest, contentDigest, validateSourcePreviewInput, type SourcePreviewInput } from "../server/accounting/source-preview-contract-v2";
import { canonicalJson, sha256, type CanonicalValue } from "../server/accounting/source-contracts";
function fail(code: string): never { throw new Error(code); }
function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) fail(`missing_argument:${name}`); return process.argv[index + 1]; }
function same(left: CanonicalValue, right: CanonicalValue): boolean { return canonicalJson(left) === canonicalJson(right); }

async function verify(client: PoolClient, inputPath: string, sourceCode: "BANK_TOSS_2026" | "BANK_IBK_2026", rowCount: number, normalizationVersion: string) {
  const input = validateSourcePreviewInput(JSON.parse(readFileSync(inputPath, "utf8"))) as SourcePreviewInput;
  if (input.source_code !== sourceCode || input.rows.length !== rowCount || input.rows.some((row) => row.normalization_version !== normalizationVersion || row.issue_status !== "warning" || row.decisions.length !== 1 || row.decisions[0].decision_kind !== "classification" || row.decisions[0].decision_payload.outcome !== "quarantine")) fail("bank_preview_input_scope_mismatch");
  if (input.rows.some((row) => canonicalJson(row.normalized_payload).match(/계좌번호|CMS코드/i) || (!row.normalized_payload.payer_name_snapshot && !row.normalized_payload.transaction_description_snapshot))) fail("bank_preview_admin_readable_boundary_mismatch");
  const expectedBatch = batchPreviewManifest(input.rows); const expectedBatchSha = sha256(canonicalJson(expectedBatch)); const expectedDecision = buildDecisionManifest(input);
  const release = await client.query<{ id: string; source_id: string }>(`SELECT r.id::text,s.id::text source_id FROM public.accounting_source_releases r JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code=$1 AND s.source_uid=$2::uuid AND r.release_uid=$3::uuid AND r.adapter_version='3.0.0' AND r.status='active'`, [input.source_code, input.source_uid, input.release_uid]); if (release.rowCount !== 1) fail("bank_preview_release_binding_mismatch");
  const batch = await client.query<{ id: string; batch_uid: string; preview_manifest: CanonicalValue; preview_manifest_sha256: string; row_count: number; warning_count: number; error_count: number; status: string }>("SELECT id::text,batch_uid::text,preview_manifest,preview_manifest_sha256,row_count,warning_count,error_count,status FROM public.accounting_import_batches WHERE source_release_id=$1 AND source_fingerprint=$2", [release.rows[0].id, input.source_fingerprint]);
  if (batch.rowCount !== 1 || batch.rows[0].batch_uid !== input.batch_uid || batch.rows[0].preview_manifest_sha256 !== expectedBatchSha || !same(batch.rows[0].preview_manifest, expectedBatch) || batch.rows[0].row_count !== rowCount || batch.rows[0].warning_count !== rowCount || batch.rows[0].error_count !== 0 || batch.rows[0].status !== "previewed") fail("bank_preview_batch_mismatch");
  const graph = await client.query<{ ordinal: number; coordinate_key: string; content_digest: string; normalized_payload: CanonicalValue; raw_payload: CanonicalValue; source_display_snapshot: string }>(`SELECT br.ordinal,c.coordinate_key,rv.content_digest,rv.normalized_payload,rv.raw_payload,rv.source_display_snapshot FROM public.accounting_import_batch_rows br JOIN public.accounting_import_coordinates c ON c.id=br.coordinate_id JOIN public.accounting_import_row_versions rv ON rv.id=br.row_version_id WHERE br.batch_id=$1 ORDER BY br.ordinal`, [batch.rows[0].id]); const expectedRows = [...input.rows].sort((a, b) => Buffer.compare(Buffer.from(a.coordinate_key), Buffer.from(b.coordinate_key)));
  if (graph.rowCount !== rowCount) fail("bank_preview_graph_count_mismatch"); for (let index = 0; index < expectedRows.length; index += 1) { const actual = graph.rows[index]; const expected = expectedRows[index]; if (actual.ordinal !== index + 1 || actual.coordinate_key !== expected.coordinate_key || actual.content_digest !== contentDigest(expected.normalized_payload) || actual.source_display_snapshot !== expected.source_display_snapshot || !same(actual.normalized_payload, expected.normalized_payload) || !same(actual.raw_payload, expected.raw_payload)) fail("bank_preview_graph_mismatch"); }
  const set = await client.query<{ decision_set_uid: string; manifest: CanonicalValue; manifest_sha256: string; status: string }>("SELECT decision_set_uid::text,manifest,manifest_sha256,status FROM public.source_decision_sets WHERE batch_id=$1", [batch.rows[0].id]); if (set.rowCount !== 1 || set.rows[0].decision_set_uid !== input.decision_set_uid || set.rows[0].manifest_sha256 !== expectedDecision.manifestSha256 || !same(set.rows[0].manifest, expectedDecision.manifest) || set.rows[0].status !== "previewed") fail("bank_preview_set_mismatch");
  const counts = (await client.query<{ items: number; receipts: number; entities: number; audits: number; coordinates: number; versions: number; links: number }>(`SELECT (SELECT count(*)::int FROM public.source_decision_items WHERE decision_set_id=(SELECT id FROM public.source_decision_sets WHERE batch_id=$1)) items,(SELECT count(*)::int FROM public.business_operation_receipts WHERE operation_uid=$2::uuid) receipts,(SELECT count(*)::int FROM public.business_operation_entities WHERE operation_uid=$2::uuid) entities,(SELECT count(*)::int FROM public.accounting_audit_events a JOIN public.business_operation_entities e ON e.action_correlation_uid=a.correlation_uid WHERE e.operation_uid=$2::uuid) audits,(SELECT count(*)::int FROM public.accounting_import_coordinates WHERE logical_source_id=$3) coordinates,(SELECT count(*)::int FROM public.accounting_import_row_versions rv JOIN public.accounting_import_coordinates c ON c.id=rv.coordinate_id WHERE c.logical_source_id=$3) versions,(SELECT count(*)::int FROM public.accounting_import_batch_rows WHERE batch_id=$1) links`, [batch.rows[0].id, input.operation_uid, release.rows[0].source_id])).rows[0];
  const expectedEntities = rowCount * 4 + 2; if (counts.items !== rowCount || counts.receipts !== 1 || counts.entities !== expectedEntities || counts.audits !== expectedEntities || counts.coordinates !== rowCount || counts.versions !== rowCount || counts.links !== rowCount) fail("bank_preview_counts_mismatch");
  return { source_code: sourceCode, source_fingerprint: input.source_fingerprint, batch_uid: input.batch_uid, decision_set_uid: input.decision_set_uid, batch_manifest_sha256: expectedBatchSha, decision_manifest_sha256: expectedDecision.manifestSha256, row_count: rowCount, decision_item_count: counts.items, operation_receipt_count: counts.receipts, result_entity_count: counts.entities, audit_count: counts.audits };
}

async function main() {
  if (arg("--target") !== "development") fail("bank_preview_verifier_scope_mismatch"); const tossPath = arg("--toss-input"); const ibkPath = arg("--ibk-input"); if (![tossPath, ibkPath].every((path) => path.startsWith("/tmp/") || path.startsWith("/private/tmp/"))) fail("bank_preview_verifier_input_must_be_ephemeral");
  const resolved = resolveDevelopmentTarget(process.env, "migration"); const pool = createTargetPool(resolved);
  try { const target = await verifyDevelopmentTarget(pool, resolved); const client = await pool.connect(); try { await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY"); const sources = [await verify(client, tossPath, "BANK_TOSS_2026", 200, "toss-bank-sheet-v3@3.0.0+reproducible-profile-v1"), await verify(client, ibkPath, "BANK_IBK_2026", 174, "ibk-bank-sheet-v3@3.0.0+reproducible-profile-v1")]; const downstream = (await client.query<{ count: number }>("SELECT ((SELECT count(*) FROM public.source_row_classification_decisions)+(SELECT count(*) FROM public.member_match_cases)+(SELECT count(*) FROM public.member_match_candidates)+(SELECT count(*) FROM public.member_position_assignments)+(SELECT count(*) FROM public.economic_events)+(SELECT count(*) FROM public.dues_receipts)+(SELECT count(*) FROM public.dues_allocations))::int count")).rows[0].count; if (downstream !== 0) fail("bank_preview_downstream_business_rows_present"); await client.query("ROLLBACK"); console.log(JSON.stringify({ schema_version: "bank-source-preview-verification-v3", target: "development", target_fingerprint: target.targetFingerprint, sources, downstream_business_row_count: downstream, terminal_transaction: "ROLLBACK", result: "verified" })); } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); } } finally { await shutdownPool(pool); }
}
main().catch((error) => { console.error(JSON.stringify({ schema_version: "bank-source-preview-verification-error-v3", error_code: error instanceof Error ? error.message : "unknown", result: "rejected" })); process.exitCode = 1; });
