import { readFileSync } from "node:fs";
import type { PoolClient } from "pg";
import { createTargetPool, resolveDevelopmentTarget, shutdownPool, verifyDevelopmentTarget } from "../server/db-target";
import { batchPreviewManifest, buildDecisionManifest, contentDigest, validateSourcePreviewInput } from "../server/accounting/source-preview-contract-v2";
import { canonicalJson, sha256, type CanonicalValue } from "../server/accounting/source-contracts";
function fail(code: string): never { throw new Error(code); }
function arg(name: string): string { const index = process.argv.indexOf(name); if (index < 0 || !process.argv[index + 1]) fail(`missing_argument:${name}`); return process.argv[index + 1]; }
function same(left: CanonicalValue, right: CanonicalValue): boolean { return canonicalJson(left) === canonicalJson(right); }

async function verify(client: PoolClient, inputPath: string) {
  const input = validateSourcePreviewInput(JSON.parse(readFileSync(inputPath, "utf8"))); if (input.source_code !== "MEMBERSHIP_INTEGRATED_ADDRESS_BOOK" || input.rows.length !== 3458 || input.rows.some((row) => row.normalization_version !== "membership-integrated-address-book-v3@3.0.0+numeric-source-cells-v1")) fail("membership_preview_input_scope_mismatch");
  const expectedBatch = batchPreviewManifest(input.rows); const expectedBatchSha = sha256(canonicalJson(expectedBatch)); const expectedDecision = buildDecisionManifest(input);
  if (expectedDecision.items.length !== 3458 || input.rows.some((row) => row.issue_status !== "warning" || row.decisions.length !== 1 || row.decisions[0].decision_payload.outcome !== "quarantine" || row.decisions[0].decision_payload.evidence_kind !== "name_only")) fail("membership_preview_quarantine_coverage_mismatch");
  const release = await client.query<{ id: string; source_id: string }>(`SELECT r.id::text,s.id::text source_id FROM public.accounting_source_releases r JOIN public.accounting_logical_sources s ON s.id=r.logical_source_id WHERE s.source_code=$1 AND s.source_uid=$2::uuid AND r.release_uid=$3::uuid AND r.adapter_version='3.0.0' AND r.status='active'`, [input.source_code, input.source_uid, input.release_uid]); if (release.rowCount !== 1) fail("membership_preview_release_binding_mismatch");
  const batch = await client.query<{ id: string; batch_uid: string; preview_manifest: CanonicalValue; preview_manifest_sha256: string; row_count: number; warning_count: number; error_count: number; status: string }>("SELECT id::text,batch_uid::text,preview_manifest,preview_manifest_sha256,row_count,warning_count,error_count,status FROM public.accounting_import_batches WHERE source_release_id=$1 AND source_fingerprint=$2", [release.rows[0].id, input.source_fingerprint]);
  if (batch.rowCount !== 1 || batch.rows[0].batch_uid !== input.batch_uid || batch.rows[0].preview_manifest_sha256 !== expectedBatchSha || !same(batch.rows[0].preview_manifest, expectedBatch) || batch.rows[0].row_count !== 3458 || batch.rows[0].warning_count !== 3458 || batch.rows[0].error_count !== 0 || batch.rows[0].status !== "previewed") fail("membership_preview_batch_mismatch");
  const graph = await client.query<{ ordinal: number; coordinate_key: string; content_digest: string; normalized_payload: CanonicalValue; raw_payload: CanonicalValue }>(`SELECT br.ordinal,c.coordinate_key,rv.content_digest,rv.normalized_payload,rv.raw_payload FROM public.accounting_import_batch_rows br JOIN public.accounting_import_coordinates c ON c.id=br.coordinate_id JOIN public.accounting_import_row_versions rv ON rv.id=br.row_version_id WHERE br.batch_id=$1 ORDER BY br.ordinal`, [batch.rows[0].id]); const expectedRows = [...input.rows].sort((a, b) => Buffer.compare(Buffer.from(a.coordinate_key), Buffer.from(b.coordinate_key)));
  if (graph.rowCount !== 3458) fail("membership_preview_graph_count_mismatch"); for (let index = 0; index < expectedRows.length; index += 1) { const actual = graph.rows[index]; const expected = expectedRows[index]; if (actual.ordinal !== index + 1 || actual.coordinate_key !== expected.coordinate_key || actual.content_digest !== contentDigest(expected.normalized_payload) || !same(actual.normalized_payload, expected.normalized_payload) || !same(actual.raw_payload, expected.raw_payload)) fail("membership_preview_graph_mismatch"); }
  const set = await client.query<{ decision_set_uid: string; manifest: CanonicalValue; manifest_sha256: string; status: string }>("SELECT decision_set_uid::text,manifest,manifest_sha256,status FROM public.source_decision_sets WHERE batch_id=$1", [batch.rows[0].id]); if (set.rowCount !== 1 || set.rows[0].decision_set_uid !== input.decision_set_uid || set.rows[0].manifest_sha256 !== expectedDecision.manifestSha256 || !same(set.rows[0].manifest, expectedDecision.manifest) || set.rows[0].status !== "previewed") fail("membership_preview_set_mismatch");
  const counts = await client.query<{ items: number; receipts: number; entities: number; audits: number; coordinates: number; versions: number; links: number; downstream: number }>(`SELECT (SELECT count(*)::int FROM public.source_decision_items WHERE decision_set_id=(SELECT id FROM public.source_decision_sets WHERE batch_id=$1)) items,(SELECT count(*)::int FROM public.business_operation_receipts WHERE operation_uid=$2::uuid) receipts,(SELECT count(*)::int FROM public.business_operation_entities WHERE operation_uid=$2::uuid) entities,(SELECT count(*)::int FROM public.accounting_audit_events a JOIN public.business_operation_entities e ON e.action_correlation_uid=a.correlation_uid WHERE e.operation_uid=$2::uuid) audits,(SELECT count(*)::int FROM public.accounting_import_coordinates WHERE logical_source_id=$3) coordinates,(SELECT count(*)::int FROM public.accounting_import_row_versions rv JOIN public.accounting_import_coordinates c ON c.id=rv.coordinate_id WHERE c.logical_source_id=$3) versions,(SELECT count(*)::int FROM public.accounting_import_batch_rows WHERE batch_id=$1) links,((SELECT count(*) FROM public.source_row_classification_decisions)+(SELECT count(*) FROM public.member_match_cases)+(SELECT count(*) FROM public.member_match_candidates)+(SELECT count(*) FROM public.member_position_assignments)+(SELECT count(*) FROM public.economic_events)+(SELECT count(*) FROM public.dues_receipts)+(SELECT count(*) FROM public.dues_allocations))::int downstream`, [batch.rows[0].id, input.operation_uid, release.rows[0].source_id]); const countsRow = counts.rows[0]; const expectedEntities = 2 + 3458 * 4;
  if (countsRow.items !== 3458 || countsRow.receipts !== 1 || countsRow.entities !== expectedEntities || countsRow.audits !== expectedEntities || countsRow.coordinates !== 3458 || countsRow.versions !== 3458 || countsRow.links !== 3458 || countsRow.downstream !== 0) fail("membership_preview_counts_mismatch");
  return { batchSha: expectedBatchSha, decisionSha: expectedDecision.manifestSha256, input, counts: countsRow };
}

async function main() {
  if (arg("--target") !== "development") fail("membership_preview_verifier_scope_mismatch"); const inputPath = arg("--input"); if (!(inputPath.startsWith("/tmp/") || inputPath.startsWith("/private/tmp/"))) fail("membership_preview_verifier_input_must_be_ephemeral");
  const resolved = resolveDevelopmentTarget(process.env, "migration"); const pool = createTargetPool(resolved);
  try { const target = await verifyDevelopmentTarget(pool, resolved); const client = await pool.connect(); try { await client.query("BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY"); const result = await verify(client, inputPath); await client.query("ROLLBACK"); console.log(JSON.stringify({ schema_version: "membership-address-book-preview-verification-v3", target: "development", target_fingerprint: target.targetFingerprint, source_fingerprint: result.input.source_fingerprint, batch_uid: result.input.batch_uid, decision_set_uid: result.input.decision_set_uid, batch_manifest_sha256: result.batchSha, decision_manifest_sha256: result.decisionSha, row_count: result.counts.versions, decision_item_count: result.counts.items, operation_receipt_count: result.counts.receipts, result_entity_count: result.counts.entities, audit_count: result.counts.audits, downstream_business_row_count: result.counts.downstream, terminal_transaction: "ROLLBACK", result: "verified" })); } catch (error) { await client.query("ROLLBACK").catch(() => undefined); throw error; } finally { client.release(); } } finally { await shutdownPool(pool); }
}
main().catch((error) => { console.error(JSON.stringify({ schema_version: "membership-address-book-preview-verification-error-v3", error_code: error instanceof Error ? error.message : "unknown", result: "rejected" })); process.exitCode = 1; });
