import { randomUUID } from "node:crypto";
import {
  createOrResumeDisposableTarget, createTargetPool, resolveDisposableControlTarget, shutdownPool,
  teardownDisposableTarget, verifyDevelopmentTarget,
} from "../server/db-target";
import { legacyCandidateLockKeys } from "../server/accounting/legacy-payment-contract";
import { buildLegacyPaymentCommand, executeLegacyPaymentCommand } from "../server/accounting/legacy-payment-service";
import { canonicalJson, type CanonicalValue } from "../server/accounting/source-contracts";
import { verifyActorReceipt, type VerifiedActor } from "./admin-actor-receipt";
import { seedLegacyNonzeroFixture } from "./verify-legacy-payment-nonzero-disposable";

function fail(code:string):never{throw new Error(code);}
function arg(name:string):string{const i=process.argv.indexOf(name);if(i<0||!process.argv[i+1])fail(`missing_argument:${name}`);return process.argv[i+1];}

async function seedAmbiguousCandidate(pool:Awaited<ReturnType<typeof createOrResumeDisposableTarget>>["pool"],actor:VerifiedActor,memberUid:string){
  const at="2026-03-02T03:00:00Z";
  const member=(await pool.query<{id:string}>("SELECT id::text FROM public.association_members WHERE member_uid=$1::uuid",[memberUid])).rows[0]??fail("legacy_failure_member_missing");
  const evidence=(await pool.query<{coordinate_id:string;row_version_id:string}>(`SELECT br.coordinate_id::text,br.row_version_id::text FROM public.accounting_import_batch_rows br JOIN public.accounting_import_batches b ON b.id=br.batch_id WHERE b.batch_uid='4aab2a7d-0984-47c2-a6f9-38b1e1ecf495' AND br.ordinal=5`)).rows[0]??fail("legacy_failure_evidence_missing");
  const event=(await pool.query<{id:string}>(`INSERT INTO public.economic_events (amount,direction,dues_year,event_kind,event_uid,occurred_at,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,reverses_event_id,status) VALUES (50000,'credit',2026,'bank',$1::uuid,'2026-03-02T12:00:00+09:00',$2::timestamptz,$3,$4::uuid,$5,'admin',$6::uuid,$7,NULL,'approved') RETURNING id::text`,[randomUUID(),at,actor.authorizationVersion,randomUUID(),actor.name,actor.userUid,actor.userId])).rows[0];
  const candidateKey=legacyCandidateLockKeys({memberUid,duesYear:2026,amount:"50000",occurredKstDate:"2026-03-01"}).find(x=>x.occurredKstDate==="2026-03-02")?.candidateKey??fail("legacy_failure_candidate_key_missing");
  await pool.query(`INSERT INTO public.economic_event_claims (amount,candidate_key,claim_actor_at,claim_actor_authorization_version,claim_actor_correlation_uid,claim_actor_name_snapshot,claim_actor_scope,claim_actor_uid_snapshot,claim_actor_user_id,claim_uid,coordinate_id,created_at,decision_actor_at,decision_actor_authorization_version,decision_actor_correlation_uid,decision_actor_name_snapshot,decision_actor_scope,decision_actor_uid_snapshot,decision_actor_user_id,direction,dues_year,effective_at,event_id,event_party_id,member_id,occurred_date_kst,party_kind,source_row_version_id,state,supersedes_id,version) VALUES (50000,$1,$2::timestamptz,$3,$4::uuid,$5,'admin',$6::uuid,$7,$8::uuid,$9,$2::timestamptz,$2::timestamptz,$3,$10::uuid,$5,'admin',$6::uuid,$7,'credit',2026,$2::timestamptz,$11,NULL,$12,'2026-03-02','member',$13,'bound',NULL,1)`,[candidateKey,at,actor.authorizationVersion,randomUUID(),actor.name,actor.userUid,actor.userId,randomUUID(),evidence.coordinate_id,randomUUID(),event.id,member.id,evidence.row_version_id]);
  const receipt=(await pool.query<{id:string}>(`INSERT INTO public.dues_receipts (event_id,gross_amount,receipt_uid,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,status,approval_actor_at,approval_actor_authorization_version,approval_actor_correlation_uid,approval_actor_name_snapshot,approval_actor_scope,approval_actor_uid_snapshot,approval_actor_user_id) VALUES ($1,50000,$2::uuid,$3::timestamptz,$4,$5::uuid,$6,'admin',$7::uuid,$8,'approved',$3::timestamptz,$4,$9::uuid,$6,'admin',$7::uuid,$8) RETURNING id::text`,[event.id,randomUUID(),at,actor.authorizationVersion,randomUUID(),actor.name,actor.userUid,actor.userId,randomUUID()])).rows[0];
  await pool.query(`INSERT INTO public.dues_allocations (allocation_kind,amount,dues_year,effect_kind,effective_at,member_id,receipt_id,recorded_actor_at,recorded_actor_authorization_version,recorded_actor_correlation_uid,recorded_actor_name_snapshot,recorded_actor_scope,recorded_actor_uid_snapshot,recorded_actor_user_id,recorded_at,request_uid,rights_effect_mode,status,approval_actor_at,approval_actor_authorization_version,approval_actor_correlation_uid,approval_actor_name_snapshot,approval_actor_scope,approval_actor_uid_snapshot,approval_actor_user_id) VALUES ('dues',50000,2026,'payment',$1::timestamptz,$2,$3,$1::timestamptz,$4,$5::uuid,$6,'admin',$7::uuid,$8,$1::timestamptz,$9::uuid,'immediate_positive','approved',$1::timestamptz,$4,$10::uuid,$6,'admin',$7::uuid,$8)`,[at,member.id,receipt.id,actor.authorizationVersion,randomUUID(),actor.name,actor.userUid,actor.userId,randomUUID(),randomUUID()]);
}

async function state(pool:Awaited<ReturnType<typeof createOrResumeDisposableTarget>>["pool"]){return (await pool.query<{phase:string;decisions:number;legacy_events:number;fence_receipts:number;payments:number}>(`SELECT (SELECT phase FROM public.legacy_cutover_states WHERE cutover_code='payments-v1' ORDER BY version DESC LIMIT 1) phase,(SELECT count(*)::int FROM public.legacy_payment_decisions) decisions,(SELECT count(*)::int FROM public.economic_events WHERE event_kind='legacy_compatibility') legacy_events,(SELECT count(*)::int FROM public.business_operation_receipts WHERE operation_uid=$1::uuid) fence_receipts,(SELECT count(*)::int FROM public.payments) payments`,[buildLegacyPaymentCommand("fence").operationUid])).rows[0];}

async function main(){
  if(arg("--target")!=="disposable-test")fail("legacy_failure_target_forbidden");const failureCase=arg("--case");if(!["ambiguous","concurrent-write"].includes(failureCase))fail("legacy_failure_case_invalid");
  const runUid=arg("--run-uid"),receiptPath=arg("--actor-receipt"),controlResolved=resolveDisposableControlTarget(process.env,runUid),controlPool=createTargetPool(controlResolved);let disposable:Awaited<ReturnType<typeof createOrResumeDisposableTarget>>|undefined;let torn=false;
  try{const development=await verifyDevelopmentTarget(controlPool,{...controlResolved,kind:"development"});disposable=await createOrResumeDisposableTarget(controlPool,development,runUid);const verified=await verifyActorReceipt(disposable.pool,receiptPath,{kind:"disposable-test",targetFingerprint:disposable.targetFingerprint,disposableRunUid:runUid,parentTargetFingerprint:disposable.parentTargetFingerprint});const actor={...verified,targetFingerprint:disposable.targetFingerprint};const fixture=await seedLegacyNonzeroFixture(disposable.pool,actor);const scope={kind:"disposable-test" as const,runUid,parentTargetFingerprint:disposable.parentTargetFingerprint};for(const action of ["register_release","preview","initialize"] as const){const result=await executeLegacyPaymentCommand(disposable.pool,buildLegacyPaymentCommand(action),actor,scope);if(result.execution_outcome!=="created")fail(`legacy_failure_setup:${action}`);}
    let errorCode="";let blockedBeforeCommit=false;
    if(failureCase==="ambiguous"){await seedAmbiguousCandidate(disposable.pool,actor,fixture.memberUid);try{await executeLegacyPaymentCommand(disposable.pool,buildLegacyPaymentCommand("fence"),actor,scope);fail("legacy_ambiguous_fence_unexpected_success");}catch(error){errorCode=error instanceof Error?error.message:"unknown";if(errorCode!=="legacy_materialization_unresolved_decision")throw error;}}
    else{const writer=await disposable.pool.connect();try{await writer.query("BEGIN");await writer.query("INSERT INTO public.payments (user_id,amount,year,type,status,created_at) VALUES (NULL,50000,2026,'연회비','completed','2026-03-20T12:00:00+09:00')");let settled=false;const fence=executeLegacyPaymentCommand(disposable.pool,buildLegacyPaymentCommand("fence"),actor,scope).then(()=>{settled=true;fail("legacy_concurrent_fence_unexpected_success");},error=>{settled=true;throw error;});await new Promise(resolve=>setTimeout(resolve,100));blockedBeforeCommit=!settled;if(!blockedBeforeCommit)fail("legacy_concurrent_writer_not_blocking_fence");await writer.query("COMMIT");try{await fence;}catch(error){errorCode=error instanceof Error?error.message:"unknown";if(errorCode!=="legacy_payment_batch_binding_mismatch")throw error;}}finally{await writer.query("ROLLBACK").catch(()=>undefined);writer.release();}}
    const after=await state(disposable.pool);const expectedPayments=failureCase==="concurrent-write"?6:5;if(canonicalJson(after as unknown as CanonicalValue)!==canonicalJson({phase:"legacy",decisions:0,legacy_events:0,fence_receipts:0,payments:expectedPayments}))fail("legacy_failure_residue_mismatch");const cleanup=await teardownDisposableTarget(controlPool,disposable);torn=cleanup.absent;console.log(canonicalJson({schema_version:"dgkma-legacy-payment-failure-disposable-v1",case:failureCase,error_code:errorCode,blocked_before_writer_commit:failureCase==="concurrent-write"?blockedBeforeCommit:null,post_failure:after,cleanup,production_operations:0,result:"approved"} as CanonicalValue));
  }finally{if(disposable&&!torn)await teardownDisposableTarget(controlPool,disposable).catch(()=>undefined);await shutdownPool(controlPool);}
}
main().catch(error=>{console.error(JSON.stringify({schema_version:"dgkma-legacy-payment-failure-disposable-error-v1",error_code:error instanceof Error?error.message:"unknown",result:"rejected"}));process.exitCode=1;});
